name: app_cnc
description: CNCIA - Assistente Industrial CNC
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  in_app_purchase: ^3.1.13
  shared_preferences: ^2.2.2
  google_mlkit_text_recognition: ^0.13.1
  google_mlkit_image_labeling: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cnc/