import 'package:flutter/foundation.dart';

enum AppIdioma { pt, en, es }

class IdiomaManager extends ChangeNotifier {
  AppIdioma _idioma = AppIdioma.pt;

  AppIdioma get idioma => _idioma;

  void setIdioma(AppIdioma novoIdioma) {
    _idioma = novoIdioma;
    notifyListeners();
  }

  String? tr(String key) => _traducoes[_idioma]?[key];

  static const Map<AppIdioma, Map<String, String>> _traducoes = {
    AppIdioma.pt: {
      'app.subtitulo': 'Assistente CNC Inteligente',
      'app.slogan': 'TECNOLOGIA PARA O CHÃO DE FÁBRICA',
      'nav.inicio': 'Início',
      'nav.biblioteca': 'Biblioteca',
      'nav.alarmes': 'Alarmes',
      'nav.ia': 'IA',
      'nav.mais': 'Mais',
      'home.bemvindo': 'Bem-vindo,',
      'home.operador': 'Operador CNC',
      'home.buscar': 'Buscar código, alarme ou material...',
      'home.online': 'Online',
      'home.offline': 'Offline',
      'home.acessorapido': 'Acesso Rápido',
      'home.recentes': 'Recentes',
      'home.analisaria': 'Análise IA para CNC',
      'home.analisaria.sub': 'Diagnóstico inteligente por foto ou texto',
      'home.guia': 'Guia Rápido',
      'home.guia.sub': 'Dicas e boas práticas para o operador',
      'home.novo': 'Ver guia',
      'ia.offline': 'Sem conexão com internet',
      'ia.offline.sub': 'A análise IA requer conexão com a internet.',
      'geral.fechar': 'Fechar',
      'geral.buscar': 'BUSCAR',
      'geral.offline.msg': 'Você está offline. Alguns recursos podem estar indisponíveis.',
      'mais.titulo': 'Ferramentas',
      'mais.ferramentas': 'Ferramentas de Cálculo',
      'mais.programacao': 'Programação CNC',
      'mais.pessoal': 'Pessoal',
      'mod.biblioteca': 'Biblioteca',
      'mod.biblioteca.sub': 'Códigos G e M completos',
      'mod.alarmes': 'Alarmes',
      'mod.alarmes.sub': '7 fabricantes catalogados',
      'mod.calculadora': 'Calculadora',
      'mod.calculadora.sub': 'RPM, avanço, rosca e mais',
      'mod.materiais': 'Materiais',
      'mod.materiais.sub': '30 materiais de usinagem',
      'mod.tabelas.sub': 'Tabelas de referência técnica',
      'mod.programas': 'Programas',
      'mod.programas.sub': 'Exemplos e templates CNC',
      'mod.favoritos': 'Favoritos',
      'mod.guia.sub': 'Dicas e boas práticas CNC',
      'calc.titulo': 'Calculadora',
      'calc.rpm': 'RPM',
      'calc.rosca': 'Rosca',
      'mat.titulo': 'Materiais',
      'tab.titulo': 'Tabelas',
      'prog.titulo': 'Programas',
      'guia.titulo': 'Guia',
      'cod.codigoG': 'Código G',
      'config.titulo': 'Configurações',
      'config.idioma': 'Idioma',
      'config.pt': 'Português',
      'config.en': 'English',
      'config.es': 'Español',
      'config.sobre': 'Sobre',
      'config.versao': 'Versão',
      'config.feito': 'Pronto',
      'config.ativo': 'ATIVO',
    },
    AppIdioma.en: {
      'app.subtitulo': 'Smart CNC Assistant',
      'app.slogan': 'TECHNOLOGY FOR THE SHOP FLOOR',
      'nav.inicio': 'Home',
      'nav.biblioteca': 'Library',
      'nav.alarmes': 'Alarms',
      'nav.ia': 'AI',
      'nav.mais': 'More',
      'home.bemvindo': 'Welcome,',
      'home.operador': 'CNC Operator',
      'home.buscar': 'Search code, alarm or material...',
      'home.online': 'Online',
      'home.offline': 'Offline',
      'home.acessorapido': 'Quick Access',
      'home.recentes': 'Recent',
      'home.analisaria': 'CNC AI Analysis',
      'home.analisaria.sub': 'Smart diagnosis by photo or text',
      'home.guia': 'Quick Guide',
      'home.guia.sub': 'Tips and best practices for operators',
      'home.novo': 'View guide',
      'ia.offline': 'No internet connection',
      'ia.offline.sub': 'AI analysis requires an internet connection.',
      'geral.fechar': 'Close',
      'geral.buscar': 'SEARCH',
      'geral.offline.msg': 'You are offline. Some features may be unavailable.',
      'mais.titulo': 'Tools',
      'mais.ferramentas': 'Calculation Tools',
      'mais.programacao': 'CNC Programming',
      'mais.pessoal': 'Personal',
      'mod.biblioteca': 'Library',
      'mod.biblioteca.sub': 'Complete G and M codes',
      'mod.alarmes': 'Alarms',
      'mod.alarmes.sub': '7 cataloged manufacturers',
      'mod.calculadora': 'Calculator',
      'mod.calculadora.sub': 'RPM, feed, thread and more',
      'mod.materiais': 'Materials',
      'mod.materiais.sub': '30 machining materials',
      'mod.tabelas.sub': 'Technical reference tables',
      'mod.programas': 'Programs',
      'mod.programas.sub': 'CNC examples and templates',
      'mod.favoritos': 'Favorites',
      'mod.guia.sub': 'CNC tips and best practices',
      'calc.titulo': 'Calculator',
      'calc.rpm': 'RPM',
      'calc.rosca': 'Thread',
      'mat.titulo': 'Materials',
      'tab.titulo': 'Tables',
      'prog.titulo': 'Programs',
      'guia.titulo': 'Guide',
      'cod.codigoG': 'G Code',
      'config.titulo': 'Settings',
      'config.idioma': 'Language',
      'config.pt': 'Português',
      'config.en': 'English',
      'config.es': 'Español',
      'config.sobre': 'About',
      'config.versao': 'Version',
      'config.feito': 'Done',
      'config.ativo': 'ACTIVE',
    },
    AppIdioma.es: {
      'app.subtitulo': 'Asistente CNC Inteligente',
      'app.slogan': 'TECNOLOGÍA PARA EL TALLER',
      'nav.inicio': 'Inicio',
      'nav.biblioteca': 'Biblioteca',
      'nav.alarmes': 'Alarmas',
      'nav.ia': 'IA',
      'nav.mais': 'Más',
      'home.bemvindo': 'Bienvenido,',
      'home.operador': 'Operador CNC',
      'home.buscar': 'Buscar código, alarma o material...',
      'home.online': 'En línea',
      'home.offline': 'Sin conexión',
      'home.acessorapido': 'Acceso Rápido',
      'home.recentes': 'Recientes',
      'home.analisaria': 'Análisis IA para CNC',
      'home.analisaria.sub': 'Diagnóstico inteligente por foto o texto',
      'home.guia': 'Guía Rápida',
      'home.guia.sub': 'Consejos y buenas prácticas para operadores',
      'home.novo': 'Ver guía',
      'ia.offline': 'Sin conexión a internet',
      'ia.offline.sub': 'El análisis IA requiere conexión a internet.',
      'geral.fechar': 'Cerrar',
      'geral.buscar': 'BUSCAR',
      'geral.offline.msg': 'Estás sin conexión. Algunas funciones pueden no estar disponibles.',
      'mais.titulo': 'Herramientas',
      'mais.ferramentas': 'Herramientas de Cálculo',
      'mais.programacao': 'Programación CNC',
      'mais.pessoal': 'Personal',
      'mod.biblioteca': 'Biblioteca',
      'mod.biblioteca.sub': 'Códigos G y M completos',
      'mod.alarmes': 'Alarmas',
      'mod.alarmes.sub': '7 fabricantes catalogados',
      'mod.calculadora': 'Calculadora',
      'mod.calculadora.sub': 'RPM, avance, rosca y más',
      'mod.materiais': 'Materiales',
      'mod.materiais.sub': '30 materiales de mecanizado',
      'mod.tabelas.sub': 'Tablas de referencia técnica',
      'mod.programas': 'Programas',
      'mod.programas.sub': 'Ejemplos y plantillas CNC',
      'mod.favoritos': 'Favoritos',
      'mod.guia.sub': 'Consejos y buenas prácticas CNC',
      'calc.titulo': 'Calculadora',
      'calc.rpm': 'RPM',
      'calc.rosca': 'Rosca',
      'mat.titulo': 'Materiales',
      'tab.titulo': 'Tablas',
      'prog.titulo': 'Programas',
      'guia.titulo': 'Guía',
      'cod.codigoG': 'Código G',
      'config.titulo': 'Configuración',
      'config.idioma': 'Idioma',
      'config.pt': 'Português',
      'config.en': 'English',
      'config.es': 'Español',
      'config.sobre': 'Acerca de',
      'config.versao': 'Versión',
      'config.feito': 'Listo',
      'config.ativo': 'ACTIVO',
    },
  };
}

final idiomaManager = IdiomaManager();
