// ─────────────────────────────────────────
// MODELOS DE DADOS
// ─────────────────────────────────────────
class CodigoItem {
  final String codigo, nome, descricao, descricaoCompleta, sintaxe, exemplo, explicacaoExemplo, categoria, maquina;
  final List<Parametro> parametros;
  final bool isG;
  // Fabricante: 'Universal', 'Fanuc', 'Siemens', 'Heidenhain', 'Haas',
  //             'Mazak', 'Okuma', 'Mitsubishi', 'Brother', 'DMG'
  final String fabricante;
  // Tipo de diagrama visual (null = sem diagrama)
  final String? diagramaTipo;
  // URL de imagem ilustrativa (pode ser asset 'assets/...' ou URL https://)
  final String? imagemUrl;
  // Legenda da imagem
  final String? imagemLegenda;
  // Dica/nota extra de uso profissional
  final String? dicaProfissional;

  const CodigoItem({
    required this.codigo, required this.nome, required this.descricao,
    required this.descricaoCompleta, required this.sintaxe, required this.exemplo,
    required this.explicacaoExemplo, required this.categoria,
    this.maquina = 'Ambos',
    required this.parametros, required this.isG,
    this.fabricante = 'Universal',
    this.diagramaTipo,
    this.imagemUrl,
    this.imagemLegenda,
    this.dicaProfissional,
  });
}

class Parametro {
  final String letra, descricao;
  const Parametro(this.letra, this.descricao);
}

class AlarmeItem {
  final String codigo, titulo, descricao, descricaoCompleta, gravidade, categoria;
  final List<String> causas, solucoes;
  final String? atencao;
  const AlarmeItem({
    required this.codigo, required this.titulo, required this.descricao,
    required this.descricaoCompleta, required this.gravidade, required this.categoria,
    required this.causas, required this.solucoes, this.atencao,
  });
}

// ─────────────────────────────────────────
// CÓDIGOS G — COMPLETO MUNDIAL
// ─────────────────────────────────────────
const codigosG = [

  // ══════ MOVIMENTO — AMBOS ══════
  CodigoItem(codigo: 'G00', nome: 'Posicionamento Rápido', categoria: 'Movimento', maquina: 'Ambos',
    descricao: 'Move todos os eixos na velocidade máxima sem cortar.',
    descricaoCompleta: 'G00 move a ferramenta até a posição programada na velocidade máxima sem corte. Modal — permanece ativo até ser substituído. Todos os eixos se movem simultaneamente.',
    sintaxe: 'G00 X[val] Y[val] Z[val]',
    parametros: [Parametro('X', 'Posição final X'), Parametro('Y', 'Posição final Y'), Parametro('Z', 'Posição final Z')],
    exemplo: 'G00 Z5.0\nG00 X0 Y0',
    explicacaoExemplo: 'Sobe Z para segurança e move para origem em velocidade máxima.',
    dicaProfissional: 'NUNCA programe G00 para dentro do material — use G01 com F programado. Sempre suba Z antes de mover em X/Y com G00 para evitar colisão com fixadores e ressaltos da peça.',
    isG: true),

  CodigoItem(codigo: 'G01', nome: 'Interpolação Linear', categoria: 'Movimento', maquina: 'Ambos',
    descricao: 'Movimento linear com corte a velocidade controlada por F.',
    descricaoCompleta: 'G01 realiza movimento linear cortando o material. Velocidade definida por F. Modal. O código de corte mais usado em CNC.',
    sintaxe: 'G01 X[val] Y[val] Z[val] F[avanço]',
    parametros: [Parametro('X', 'Posição final X'), Parametro('Y', 'Posição final Y'), Parametro('Z', 'Profundidade'), Parametro('F', 'Avanço mm/min ou mm/rot')],
    exemplo: 'G01 Z-3.0 F100\nG01 X50.0 F200',
    explicacaoExemplo: 'Desce 3mm a 100mm/min e corta até X=50mm a 200mm/min.',
    dicaProfissional: 'Para fresamento em rampa (ramp-in), combine G01 X e Z simultaneamente para evitar furar direto no material: G01 X30. Z-3. F150. Reduz carga axial na fresa.',
    isG: true),

  CodigoItem(codigo: 'G02', nome: 'Interpolação Circular Horária', categoria: 'Movimento', maquina: 'Ambos',
    descricao: 'Arco no sentido horário com corte. Pode usar R ou I,J,K.',
    descricaoCompleta: 'G02 executa arco horário (CW). R = raio direto. I,J = distância ao centro. O plano deve ser selecionado com G17/G18/G19.',
    sintaxe: 'G02 X[fim] Y[fim] R[raio] F[av]\nG02 X[fim] Y[fim] I[dx] J[dy] F[av]',
    parametros: [Parametro('R', 'Raio (+ = arco <180°, - = arco >180°)'), Parametro('I', 'Distância ao centro em X'), Parametro('J', 'Distância ao centro em Y')],
    exemplo: 'G02 X30.0 Y0 R15.0 F150\nG02 X30.0 Y0 I15.0 J0 F150',
    explicacaoExemplo: 'Arco horário raio 15mm — R e I,J produzem o mesmo resultado.',
    dicaProfissional: 'Para círculo completo (360°) NUNCA use R — use I,J. Com R o CNC não sabe qual caminho tomar no círculo completo. Exemplo: G02 I15. (circulo completo raio 15mm partindo da posição atual).',
    isG: true),

  CodigoItem(codigo: 'G03', nome: 'Interpolação Circular Anti-horária', categoria: 'Movimento', maquina: 'Ambos',
    descricao: 'Arco no sentido anti-horário com corte.',
    descricaoCompleta: 'G03 é igual ao G02 mas no sentido anti-horário (CCW). Usado para raios internos, bolsões e perfis côncavos.',
    sintaxe: 'G03 X[fim] Y[fim] R[raio] F[av]',
    parametros: [Parametro('R', 'Raio mm'), Parametro('I/J', 'Coordenadas do centro')],
    exemplo: 'G03 X0 Y30.0 R15.0 F150',
    explicacaoExemplo: 'Arco anti-horário raio 15mm para perfis internos.', isG: true),

  CodigoItem(codigo: 'G04', nome: 'Pausa Temporizada (Dwell)', categoria: 'Movimento', maquina: 'Ambos',
    descricao: 'Para todos os movimentos por um tempo determinado.',
    descricaoCompleta: 'G04 provoca pausa no programa pelo tempo especificado. Útil para garantir que a ferramenta complete o corte antes de retrair.',
    sintaxe: 'G04 P[ms] ou G04 X[seg]',
    parametros: [Parametro('P', 'Tempo em milissegundos (P1000 = 1s)'), Parametro('X', 'Tempo em segundos')],
    exemplo: 'G01 Z-10. F100\nG04 P500\nG00 Z5.',
    explicacaoExemplo: 'Perfura, pausa 0.5s para limpar o fundo e retrai.', isG: true),

  // ══════ PLANOS ══════
  CodigoItem(codigo: 'G17', nome: 'Plano XY — Fresamento', categoria: 'Planos', maquina: 'Ambos',
    descricao: 'Seleciona plano XY para arcos e compensação de raio. Padrão fresamento.',
    descricaoCompleta: 'G17 seleciona o plano XY. Padrão para centros de usinagem verticais. Obrigatório antes de G02/G03 e G41/G42.',
    sintaxe: 'G17', parametros: [],
    exemplo: 'G17\nG02 X30. Y0 R15. F150',
    explicacaoExemplo: 'Plano XY ativo — padrão fresamento vertical.', isG: true),

  CodigoItem(codigo: 'G18', nome: 'Plano XZ — Torneamento', categoria: 'Planos', maquina: 'Ambos',
    descricao: 'Seleciona plano XZ para arcos. Padrão para tornos CNC.',
    descricaoCompleta: 'G18 seleciona o plano XZ. Padrão para tornos. Necessário para arcos G02/G03 no perfil longitudinal.',
    sintaxe: 'G18', parametros: [],
    exemplo: 'G18\nG02 X30. Z-5. R10. F100',
    explicacaoExemplo: 'Plano XZ — arco no torneamento.', isG: true),

  CodigoItem(codigo: 'G19', nome: 'Plano YZ', categoria: 'Planos', maquina: 'Ambos',
    descricao: 'Seleciona plano YZ para arcos em fresamento lateral.',
    descricaoCompleta: 'G19 seleciona o plano YZ. Usado em fresamento lateral e máquinas 5 eixos.',
    sintaxe: 'G19', parametros: [],
    exemplo: 'G19\nG02 Y20. Z-5. R10. F100',
    explicacaoExemplo: 'Plano YZ para 5 eixos.', isG: true),

  // ══════ UNIDADES ══════
  CodigoItem(codigo: 'G20', nome: 'Unidade em Polegadas', categoria: 'Configuração', maquina: 'Ambos',
    descricao: 'Define todas as medidas em polegadas (sistema imperial).',
    descricaoCompleta: 'Com G20, todos os valores são em polegadas. Nunca misture G20 e G21 no mesmo programa.',
    sintaxe: 'G20', parametros: [],
    exemplo: 'G20\nG00 X1.0 Y0.5',
    explicacaoExemplo: 'X1.0 = 25.4mm — sistema imperial.', isG: true),

  CodigoItem(codigo: 'G21', nome: 'Unidade em Milímetros', categoria: 'Configuração', maquina: 'Ambos',
    descricao: 'Define todas as medidas em mm. Padrão mundial.',
    descricaoCompleta: 'Com G21, todos os valores são em mm. Sempre declarar no início do programa.',
    sintaxe: 'G21', parametros: [],
    exemplo: 'G21\nG00 X50. Y25.',
    explicacaoExemplo: 'Padrão no Brasil e no mundo.', isG: true),

  // ══════ COMPENSAÇÃO — CENTRO ══════
  CodigoItem(codigo: 'G40', nome: 'Cancela Compensação de Raio', categoria: 'Compensação', maquina: 'Centro de Usinagem',
    descricao: 'Desativa G41 ou G42.',
    descricaoCompleta: 'G40 cancela compensação de raio. Deve ser usado com movimento G00 ou G01 para saída correta.',
    sintaxe: 'G40 G00 X[val]', parametros: [],
    exemplo: 'G01 X50. F200\nG40 G00 X60.',
    explicacaoExemplo: 'Cancela compensação e afasta — sempre com movimento.', isG: true),

  CodigoItem(codigo: 'G41', nome: 'Compensação de Raio — Esquerda', categoria: 'Compensação', maquina: 'Centro de Usinagem',
    descricao: 'Posiciona fresa à esquerda do perfil. Compensa o raio automaticamente.',
    descricaoCompleta: 'G41 desloca o centro da fresa para a esquerda da trajetória pelo valor D. Permite trocar a fresa sem reprogramar o perfil.',
    sintaxe: 'G41 D[n] G01 X[val] F[av]',
    parametros: [Parametro('D', 'Offset de raio na tabela — valor = raio da fresa')],
    exemplo: 'G41 D01 G01 X10. F200\nG01 Y50.\nG40 G00 X60.',
    explicacaoExemplo: 'Ativa D01, usina contorno e cancela com G40.', isG: true),

  CodigoItem(codigo: 'G42', nome: 'Compensação de Raio — Direita', categoria: 'Compensação', maquina: 'Centro de Usinagem',
    descricao: 'Posiciona fresa à direita do perfil.',
    descricaoCompleta: 'G42 é igual ao G41 mas à direita da trajetória.',
    sintaxe: 'G42 D[n] G01 X[val] F[av]',
    parametros: [Parametro('D', 'Offset de raio')],
    exemplo: 'G42 D01 G01 X10. F200\nG40 G00 X60.',
    explicacaoExemplo: 'Fresa pelo lado direito do perfil.', isG: true),

  CodigoItem(codigo: 'G43', nome: 'Compensação de Comprimento +', categoria: 'Compensação', maquina: 'Ambos',
    descricao: 'Ativa compensação de comprimento de ferramenta. Essencial após troca.',
    descricaoCompleta: 'G43 soma o valor H ao eixo Z. Permite usar ferramentas de comprimentos diferentes sem reprogramar.',
    sintaxe: 'G43 H[n] Z[val]',
    parametros: [Parametro('H', 'Número do offset de comprimento'), Parametro('Z', 'Posição Z inicial')],
    exemplo: 'T01 M06\nG43 H01 Z100.',
    explicacaoExemplo: 'Troca T1 e ativa compensação H01.', isG: true),

  CodigoItem(codigo: 'G44', nome: 'Compensação de Comprimento —', categoria: 'Compensação', maquina: 'Ambos',
    descricao: 'Ativa compensação negativa de comprimento.',
    descricaoCompleta: 'G44 subtrai o valor H do eixo Z. Menos comum — para casos onde compensação é negativa.',
    sintaxe: 'G44 H[n] Z[val]',
    parametros: [Parametro('H', 'Offset'), Parametro('Z', 'Posição Z')],
    exemplo: 'G44 H02 Z50.',
    explicacaoExemplo: 'Compensação negativa.', isG: true),

  CodigoItem(codigo: 'G49', nome: 'Cancela Compensação de Comprimento', categoria: 'Compensação', maquina: 'Centro de Usinagem',
    descricao: 'Desativa G43 ou G44.',
    descricaoCompleta: 'G49 cancela a compensação de comprimento ativa.',
    sintaxe: 'G49', parametros: [],
    exemplo: 'G28 Z0\nG49',
    explicacaoExemplo: 'Retorna ao zero e cancela compensação.', isG: true),

  // ══════ CICLOS FIXOS — CENTRO ══════
  CodigoItem(codigo: 'G73', nome: 'Furação com Quebra de Cavaco', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Furação profunda com retrações parciais para quebrar cavaco. Mais rápido que G83.',
    descricaoCompleta: 'G73 faz furação profunda com pequenas retrações (não sai do furo) a cada passo Q para quebrar o cavaco. Ideal para materiais de cavaco longo como inox.',
    sintaxe: 'G73 X[pos] Y[pos] Z[prof] R[plano] Q[passo] F[av]',
    parametros: [Parametro('Z', 'Profundidade final'), Parametro('R', 'Plano de retorno'), Parametro('Q', 'Passo por perfurada'), Parametro('F', 'Avanço')],
    exemplo: 'G73 X20. Y15. Z-30. R2. Q5. F80\nG80',
    explicacaoExemplo: 'Furo 30mm — desce 5mm por vez quebrando cavaco.', isG: true),

  CodigoItem(codigo: 'G74', nome: 'Rosqueamento Esquerdo', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Ciclo automático de rosqueamento com macho esquerdo (M04).',
    descricaoCompleta: 'G74 executa rosqueamento anti-horário. Spindle inverte automaticamente na retração. F = passo × RPM.',
    sintaxe: 'G74 X[pos] Y[pos] Z[prof] R[plano] F[av]',
    parametros: [Parametro('Z', 'Profundidade'), Parametro('F', 'Passo × RPM')],
    exemplo: 'S500 M04\nG74 X20. Y15. Z-20. R2. F0.75\nG80',
    explicacaoExemplo: 'Rosca esquerda passo 0.75 a 500 RPM.', isG: true),

  CodigoItem(codigo: 'G76', nome: 'Mandrilamento Fino', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Mandrilamento com recuo orientado — não risca a superfície do furo.',
    descricaoCompleta: 'G76 para o spindle em posição angular (M19) antes de retrair, deslocando para não riscar. Para furos de alta precisão Ra < 0.8μm.',
    sintaxe: 'G76 X[pos] Y[pos] Z[prof] R[plano] Q[desl] F[av]',
    parametros: [Parametro('Q', 'Deslocamento de recuo em μm'), Parametro('F', 'Avanço')],
    exemplo: 'G76 X50. Y30. Z-25. R2. Q100 F50\nG80',
    explicacaoExemplo: 'Mandrila, orienta spindle, desloca 0.1mm e retrai sem riscar.', isG: true),

  CodigoItem(codigo: 'G80', nome: 'Cancela Ciclo Fixo', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Cancela qualquer ciclo fixo ativo (G73 a G89). SEMPRE usar ao final.',
    descricaoCompleta: 'G80 desativa o ciclo fixo. Sem G80, o CNC continua executando o ciclo em cada novo bloco de posicionamento.',
    sintaxe: 'G80', parametros: [],
    exemplo: 'G81 X10. Z-15. R2. F100\nX20. X30.\nG80',
    explicacaoExemplo: 'Faz furos e cancela o ciclo.', isG: true),

  CodigoItem(codigo: 'G81', nome: 'Furação Simples', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Ciclo básico de furação — desce, fura e retrai rapidamente.',
    descricaoCompleta: 'G81 é o ciclo de furação mais usado. Desce com F até Z, retrai em G00 até R. Ideal para furos rasos (L/D < 3).',
    sintaxe: 'G81 X[pos] Y[pos] Z[prof] R[plano] F[av]',
    parametros: [Parametro('Z', 'Profundidade'), Parametro('R', 'Plano de retorno'), Parametro('F', 'Avanço')],
    exemplo: 'G81 X10. Y10. Z-15. R2. F100\nX20. Y10.\nG80',
    explicacaoExemplo: 'Faz furos de 15mm de profundidade.', isG: true),

  CodigoItem(codigo: 'G82', nome: 'Furação com Pausa (Counterbore)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Furação com pausa P no fundo — ideal para rebaixos e escareados.',
    descricaoCompleta: 'G82 é igual ao G81 mas com pausa P no fundo. Melhora o acabamento e limpa o fundo do furo. Muito usado para rebaixos.',
    sintaxe: 'G82 X[pos] Y[pos] Z[prof] R[plano] P[pausa] F[av]',
    parametros: [Parametro('P', 'Pausa ms (P500 = 0.5s)'), Parametro('F', 'Avanço')],
    exemplo: 'G82 X15. Y20. Z-10. R2. P500 F80\nG80',
    explicacaoExemplo: 'Fura, pausa 0.5s limpando fundo do rebaixo.', isG: true),

  CodigoItem(codigo: 'G83', nome: 'Furação Profunda (Peck Drilling)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Furação profunda com retração total a cada passo — evacua cavaco.',
    descricaoCompleta: 'G83 sai completamente do furo a cada passo Q para evacuação total do cavaco. Obrigatório para furos profundos (L/D > 5).',
    sintaxe: 'G83 X[pos] Y[pos] Z[prof] R[plano] Q[passo] F[av]',
    parametros: [Parametro('Q', 'Passo de perfuração'), Parametro('F', 'Avanço')],
    exemplo: 'G83 X25. Y25. Z-50. R2. Q8. F60\nG80',
    explicacaoExemplo: 'Furo 50mm: desce 8mm, retrai totalmente, repete.', isG: true),

  CodigoItem(codigo: 'G84', nome: 'Rosqueamento Direito (Tapping)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Rosqueamento automático com macho direito. F = passo × RPM — CRÍTICO.',
    descricaoCompleta: 'G84 executa rosqueamento horário. Inverte automaticamente para retrair. F = passo × RPM. Use M49 para travar override.',
    sintaxe: 'G84 X[pos] Y[pos] Z[prof] R[plano] F[av]',
    parametros: [Parametro('F', 'CRÍTICO: F = passo × RPM (ex: M10×1.5 a 300RPM → F=450)')],
    exemplo: 'M49\nS300 M03\nG84 X20. Y15. Z-20. R5. F450\nG80\nM48',
    explicacaoExemplo: 'M10×1.5 a 300RPM: F=300×1.5=450mm/min.', isG: true),

  CodigoItem(codigo: 'G85', nome: 'Mandrilamento (entrada e saída com avanço)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Mandrila descendo e sobe também com avanço F.',
    descricaoCompleta: 'G85 entra e sai com mesmo avanço F. Acabamento em ambas as direções.',
    sintaxe: 'G85 X[pos] Y[pos] Z[prof] R[plano] F[av]',
    parametros: [Parametro('F', 'Avanço entrada e saída')],
    exemplo: 'G85 X30. Y20. Z-20. R2. F60\nG80',
    explicacaoExemplo: 'Mandrila e retrai com F60 nos dois sentidos.', isG: true),

  CodigoItem(codigo: 'G86', nome: 'Mandrilamento (para spindle ao subir)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Mandrila, para o spindle e retrai rapidamente.',
    descricaoCompleta: 'G86 mandrila até Z, para spindle (M05) e retrai em G00.',
    sintaxe: 'G86 X[pos] Y[pos] Z[prof] R[plano] F[av]',
    parametros: [Parametro('F', 'Avanço')],
    exemplo: 'G86 X40. Y20. Z-15. R2. F50\nG80',
    explicacaoExemplo: 'Mandrila, para spindle e retrai.', isG: true),

  CodigoItem(codigo: 'G89', nome: 'Mandrilamento com Pausa', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Mandrila com pausa no fundo e retração com avanço.',
    descricaoCompleta: 'G89 combina G85 com pausa P no fundo para melhor acabamento.',
    sintaxe: 'G89 X[pos] Y[pos] Z[prof] R[plano] P[pausa] F[av]',
    parametros: [Parametro('P', 'Pausa ms'), Parametro('F', 'Avanço')],
    exemplo: 'G89 X30. Y20. Z-20. R2. P300 F50\nG80',
    explicacaoExemplo: 'Mandrila, pausa 300ms e retrai com avanço.', isG: true),

  CodigoItem(codigo: 'G98', nome: 'Retorno ao Plano Inicial (ciclos)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Após cada furo, retorna ao plano inicial. Mais seguro.',
    descricaoCompleta: 'G98 faz Z retornar ao plano onde estava antes do ciclo. Mais seguro quando há obstáculos entre furos.',
    sintaxe: 'G98\nG81 X[pos] Z[prof] R[plano] F[av]',
    parametros: [],
    exemplo: 'G98\nG81 X10. Z-15. R2. F100\nX50.\nG80',
    explicacaoExemplo: 'Seguro para furos com obstáculos entre eles.', isG: true),

  CodigoItem(codigo: 'G99', nome: 'Retorno ao Plano R (ciclos)', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Após cada furo, retorna apenas ao plano R. Mais rápido.',
    descricaoCompleta: 'G99 faz Z retornar apenas ao plano R entre furos. Mais rápido para furos próximos sem obstáculos.',
    sintaxe: 'G99\nG81 X[pos] Z[prof] R[plano] F[av]',
    parametros: [],
    exemplo: 'G99\nG81 X10. Z-15. R2. F100\nX20.\nG80',
    explicacaoExemplo: 'Mais rápido entre furos próximos sem obstáculos.', isG: true),

  // ══════ REFERÊNCIA E ZERO-PEÇA ══════
  CodigoItem(codigo: 'G28', nome: 'Retorno ao Zero Máquina', categoria: 'Referência', maquina: 'Ambos',
    descricao: 'Retorna eixos ao zero da máquina via ponto intermediário.',
    descricaoCompleta: 'G28 envia eixos ao ponto de referência (home) passando por ponto intermediário. Sempre Z primeiro.',
    sintaxe: 'G28 Z0\nG28 X0 Y0',
    parametros: [],
    exemplo: 'G28 Z0\nG28 X0 Y0',
    explicacaoExemplo: 'Z primeiro para evitar colisão com a peça.', isG: true),

  CodigoItem(codigo: 'G30', nome: 'Retorno ao 2º Ponto de Referência', categoria: 'Referência', maquina: 'Torno CNC',
    descricao: 'Vai ao segundo ponto de referência — posição de troca no torno.',
    descricaoCompleta: 'G30 vai ao segundo ponto de referência. Usado em tornos para posição de troca de ferramenta.',
    sintaxe: 'G30 Z0', parametros: [],
    exemplo: 'G30 Z0\nT0202',
    explicacaoExemplo: 'Posição de troca e seleciona T2.', isG: true),

  CodigoItem(codigo: 'G52', nome: 'Sistema de Coordenadas Local', categoria: 'Zero-Peça', maquina: 'Centro de Usinagem',
    descricao: 'Cria offset temporário de coordenadas dentro do programa.',
    descricaoCompleta: 'G52 define zero temporário deslocado do atual. Útil para features repetitivas em posições diferentes.',
    sintaxe: 'G52 X[off] Y[off] Z[off]',
    parametros: [Parametro('X/Y/Z', 'Deslocamento do novo zero temporário')],
    exemplo: 'G52 X50. Y30.\nG81 X0 Y0 Z-10. R2. F100\nG52 X0 Y0',
    explicacaoExemplo: 'Move zero para X50,Y30, faz operação e restaura.', isG: true),

  CodigoItem(codigo: 'G53', nome: 'Coordenadas da Máquina', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Move em coordenadas absolutas da máquina ignorando offsets.',
    descricaoCompleta: 'G53 usa coordenadas absolutas da máquina. Não modal — válido apenas no bloco programado.',
    sintaxe: 'G53 G00 Z[val]', parametros: [],
    exemplo: 'G53 G00 Z0',
    explicacaoExemplo: 'Vai ao Z zero absoluto ignorando G54-G59.', isG: true),

  CodigoItem(codigo: 'G54', nome: 'Zero-Peça 1', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Ativa o primeiro sistema de coordenadas de trabalho. O mais usado.',
    descricaoCompleta: 'G54 é o zero-peça mais usado. Armazena a posição do zero da peça configurada no setup.',
    sintaxe: 'G54', parametros: [],
    exemplo: 'G54\nG00 X0 Y0 Z5.',
    explicacaoExemplo: 'Ativa zero-peça 1 e vai à origem.', isG: true),

  CodigoItem(codigo: 'G55', nome: 'Zero-Peça 2', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Segundo sistema de coordenadas — segunda fixação ou peça.',
    descricaoCompleta: 'G55 para segunda fixação. Cada G5x tem seus próprios offsets X,Y,Z.',
    sintaxe: 'G55', parametros: [],
    exemplo: 'G54  ; Peça 1\nG55  ; Peça 2\nG00 X0 Y0',
    explicacaoExemplo: 'Troca para segunda fixação sem alterar programa.', isG: true),

  CodigoItem(codigo: 'G56', nome: 'Zero-Peça 3', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Terceiro sistema de coordenadas.', descricaoCompleta: 'Terceiro offset de zero-peça.',
    sintaxe: 'G56', parametros: [], exemplo: 'G56\nG00 X0 Y0', explicacaoExemplo: 'Terceira fixação.', isG: true),

  CodigoItem(codigo: 'G57', nome: 'Zero-Peça 4', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Quarto sistema de coordenadas.', descricaoCompleta: 'Quarto offset.',
    sintaxe: 'G57', parametros: [], exemplo: 'G57\nG00 X0 Y0', explicacaoExemplo: 'Quarta fixação.', isG: true),

  CodigoItem(codigo: 'G58', nome: 'Zero-Peça 5', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Quinto sistema de coordenadas.', descricaoCompleta: 'Quinto offset.',
    sintaxe: 'G58', parametros: [], exemplo: 'G58\nG00 X0 Y0', explicacaoExemplo: 'Quinta fixação.', isG: true),

  CodigoItem(codigo: 'G59', nome: 'Zero-Peça 6', categoria: 'Zero-Peça', maquina: 'Ambos',
    descricao: 'Sexto sistema de coordenadas padrão.', descricaoCompleta: 'Sexto offset. Para mais: G54.1 P1-P48.',
    sintaxe: 'G59', parametros: [], exemplo: 'G59\nG00 X0 Y0', explicacaoExemplo: 'Sexta fixação.', isG: true),

  CodigoItem(codigo: 'G54.1', nome: 'Zero-Peça Estendido P1-P48', categoria: 'Zero-Peça', maquina: 'Centro de Usinagem',
    descricao: 'Até 48 zeros-peça adicionais. Ideal para paletes e automação.',
    descricaoCompleta: 'G54.1 P1-P48 permite até 48 sistemas adicionais. Para linhas automáticas e paletes.',
    sintaxe: 'G54.1 P[1-48]',
    parametros: [Parametro('P', 'Número do zero-peça adicional (1-48)')],
    exemplo: 'G54.1 P1\nG54.1 P10',
    explicacaoExemplo: 'Zeros-peça extras para linha automática.', isG: true),

  // ══════ PROGRAMAÇÃO ══════
  CodigoItem(codigo: 'G90', nome: 'Programação Absoluta', categoria: 'Programação', maquina: 'Ambos',
    descricao: 'Coordenadas medidas do zero-peça. Modo padrão e mais usado.',
    descricaoCompleta: 'No G90, cada coordenada é medida do zero-peça. X50 = ir para 50mm do zero.',
    sintaxe: 'G90', parametros: [],
    exemplo: 'G90\nG00 X50. Y30.',
    explicacaoExemplo: 'X50 = 50mm do zero, independente de onde está.', isG: true),

  CodigoItem(codigo: 'G91', nome: 'Programação Incremental', categoria: 'Programação', maquina: 'Ambos',
    descricao: 'Coordenadas relativas à posição atual da ferramenta.',
    descricaoCompleta: 'No G91, cada coordenada é deslocamento da posição atual. Útil para padrões repetitivos.',
    sintaxe: 'G91', parametros: [],
    exemplo: 'G91\nG01 X10. F200\nG01 X10.',
    explicacaoExemplo: 'Anda 10mm, depois mais 10mm.', isG: true),

  CodigoItem(codigo: 'G92', nome: 'Define Coordenada / Limita RPM Torno', categoria: 'Programação', maquina: 'Ambos',
    descricao: 'Redefine coordenadas sem mover ou limita RPM máximo no torno com G96.',
    descricaoCompleta: 'G92: (1) Redefine coordenadas sem mover. (2) No torno com G96, G92 S[RPM] limita RPM máximo.',
    sintaxe: 'G92 X[val] Z[val]  ; Redefine\nG92 S[RPM]          ; Limita RPM (torno)',
    parametros: [Parametro('S', 'RPM máximo com G96 ativo no torno')],
    exemplo: 'G96 S200\nG92 S3000  ; Nunca passa de 3000 RPM',
    explicacaoExemplo: 'Protege spindle de velocidade excessiva em diâmetros pequenos.', isG: true),

  // ══════ AVANÇO ══════
  CodigoItem(codigo: 'G93', nome: 'Avanço por Tempo Inverso (5 eixos)', categoria: 'Avanço', maquina: 'Centro de Usinagem',
    descricao: 'F = movimentos completos por minuto. Usado em usinagem de 5 eixos.',
    descricaoCompleta: 'G93 define avanço como número de movimentos completos por minuto. Necessário em 5 eixos para manter velocidade constante quando o comprimento do vetor varia.',
    sintaxe: 'G93 G01 X[val] F[n]',
    parametros: [Parametro('F', 'Movimentos por minuto — quanto maior F, mais rápido')],
    exemplo: 'G93 G01 X100. Y50. Z-10. A30. F10\n; F10 = 10 movimentos completos/min',
    explicacaoExemplo: 'Essencial em 5 eixos para velocidade de corte constante.', isG: true),

  CodigoItem(codigo: 'G94', nome: 'Avanço por Minuto (mm/min)', categoria: 'Avanço', maquina: 'Ambos',
    descricao: 'F em milímetros por minuto. Padrão para fresamento.',
    descricaoCompleta: 'G94 é o modo padrão para centros de usinagem. F = mm/min diretamente.',
    sintaxe: 'G94', parametros: [],
    exemplo: 'G94\nG01 X50. F200',
    explicacaoExemplo: '200mm por minuto — padrão de fresamento.', isG: true),

  CodigoItem(codigo: 'G95', nome: 'Avanço por Rotação (mm/rot)', categoria: 'Avanço', maquina: 'Torno CNC',
    descricao: 'F em milímetros por rotação. Padrão para torneamento.',
    descricaoCompleta: 'G95 define F como mm por rotação. Garante avanço proporcional ao RPM — se RPM muda, avanço em mm/min muda mas mm/rot é constante.',
    sintaxe: 'G95', parametros: [],
    exemplo: 'G95\nG01 Z-50. F0.2',
    explicacaoExemplo: '0.2mm a cada rotação — padrão torneamento.', isG: true),

  CodigoItem(codigo: 'G96', nome: 'Velocidade de Corte Constante CSS', categoria: 'Velocidade', maquina: 'Torno CNC',
    descricao: 'Mantém Vc constante variando RPM automaticamente. Essencial no torno.',
    descricaoCompleta: 'G96 varia RPM para manter S (m/min) constante enquanto diâmetro muda. Garante acabamento uniforme do centro à borda.',
    sintaxe: 'G96 S[m/min]',
    parametros: [Parametro('S', 'Velocidade de corte em m/min')],
    exemplo: 'G96 S200\nG92 S3000\nG01 X0 F0.15',
    explicacaoExemplo: 'Mantém 200m/min — RPM sobe quando diâmetro reduz.', isG: true),

  CodigoItem(codigo: 'G97', nome: 'RPM Constante — cancela G96', categoria: 'Velocidade', maquina: 'Ambos',
    descricao: 'S em RPM fixo. Padrão para fresamento. OBRIGATÓRIO em rosqueamento.',
    descricaoCompleta: 'G97 cancela G96 e define RPM fixo. S = RPM diretamente. Sempre usar em rosqueamento.',
    sintaxe: 'G97 S[RPM]',
    parametros: [Parametro('S', 'RPM desejado')],
    exemplo: 'G97 S1500\nG01 X50. F200',
    explicacaoExemplo: 'Fixa 1500 RPM — padrão fresamento e rosqueamento.', isG: true),

  // ══════ CICLOS TORNO FANUC ══════
  CodigoItem(codigo: 'G32', nome: 'Rosca Direta — Passe Único (Torno)', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Executa um único passe de rosca. Sem retorno automático — posicionamento manual.',
    descricaoCompleta: 'G32 realiza um único passe de rosca. Diferente do G92 (retorno automático) e G76 (multiciclo): o programador controla cada movimento manualmente. F = passo da rosca. RPM FIXO obrigatório (G97). Mais trabalhoso, mas permite roscas cônicas, multi-lead e passo variável.',
    sintaxe: 'G32 X[diâm] Z[compr] F[passo]',
    parametros: [Parametro('X', 'Diâmetro do passe'), Parametro('Z', 'Comprimento da rosca'), Parametro('F', 'Passo da rosca em mm — IGUAL ao passo físico')],
    exemplo: 'G97 S400 M03  ; RPM fixo obrigatório\nG00 X19.4\nG32 Z-40. F2.5  ; Passe 1\nG00 X25. Z5.    ; Retira e volta\nX18.9\nG32 Z-40. F2.5  ; Passe 2\nG00 X25. Z5.\nX16.93\nG32 Z-40. F2.5  ; Passe final\nG00 X25.',
    explicacaoExemplo: 'G32 faz só o corte — G00 cuida do recuo e reposicionamento manualmente. Para rosca M20×2.5.',
    dicaProfissional: 'Prefira G92 (retorno auto) ou G76 (multiciclo completo). Use G32 quando precisar de trajetória customizada: rosca cônica (X e Z simultâneos), rosca multi-lead (offset Z entre leads) ou passo variável — impossíveis com G76.',
    isG: true),

  CodigoItem(codigo: 'G70', nome: 'Ciclo de Acabamento — Torno Fanuc', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Executa passe de acabamento após desbaste com G71/G72/G73.',
    descricaoCompleta: 'G70 faz o passe fino seguindo o perfil definido entre P e Q. Usar sempre após G71 ou G72 com pastilha de acabamento.',
    sintaxe: 'G70 P[início] Q[fim]',
    parametros: [Parametro('P', 'Bloco inicial do perfil'), Parametro('Q', 'Bloco final do perfil')],
    exemplo: 'G71 U2. R0.5\nG71 P10 Q20 U0.4 W0.1 F0.3\n...\nG70 P10 Q20',
    explicacaoExemplo: 'G71 faz desbaste, G70 faz acabamento no mesmo perfil com outra pastilha.', isG: true),

  CodigoItem(codigo: 'G71', nome: 'Desbaste Longitudinal — Torno Fanuc', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Desbaste automático paralelo ao eixo Z. O ciclo mais usado em torneamento.',
    descricaoCompleta: 'G71 executa passes de desbaste paralelos ao Z automaticamente, seguindo o perfil entre P e Q. Fundamental para torneamento Fanuc.',
    sintaxe: 'G71 U[ap] R[recuo]\nG71 P[ini] Q[fim] U[sobr X] W[sobr Z] F[av]',
    parametros: [Parametro('U', 'Profundidade por passe ap'), Parametro('R', 'Recuo entre passes'), Parametro('P/Q', 'Blocos do perfil'), Parametro('U sobr.', 'Sobremetal em X para G70'), Parametro('W', 'Sobremetal em Z')],
    exemplo: 'G71 U2. R0.5\nG71 P100 Q200 U0.4 W0.1 F0.25\nN100 G00 X22.\nG01 Z-30.\nN200 X62.',
    explicacaoExemplo: 'Desbaste em passes de 2mm, deixa 0.4mm para G70.', isG: true),

  CodigoItem(codigo: 'G72', nome: 'Desbaste Transversal — Torno Fanuc', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Desbaste automático paralelo ao eixo X — faceamento de discos.',
    descricaoCompleta: 'G72 executa passes paralelos ao X. Para faceamento de peças com grande diâmetro e pouca profundidade axial.',
    sintaxe: 'G72 W[ap] R[recuo]\nG72 P[ini] Q[fim] U[sobr] W[sobr] F[av]',
    parametros: [Parametro('W', 'Profundidade axial por passe'), Parametro('R', 'Recuo')],
    exemplo: 'G72 W1.5 R0.5\nG72 P100 Q200 U0.3 W0.1 F0.20',
    explicacaoExemplo: 'Desbaste transversal para faceamento de disco grande.', isG: true),

  CodigoItem(codigo: 'G73', nome: 'Desbaste por Cópia de Perfil — Torno Fanuc', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Desbaste paralelo ao perfil — ideal para fundidos e forjados.',
    descricaoCompleta: 'G73 (torno) executa passes paralelos ao perfil. Ideal para peças pré-formadas onde o sobremetal é uniforme. DIFERENTE do G73 de furação!',
    sintaxe: 'G73 U[deslocX] W[deslocZ] R[passes]\nG73 P[ini] Q[fim] U[sobr] W[sobr] F[av]',
    parametros: [Parametro('U', 'Deslocamento X da 1ª passada'), Parametro('W', 'Deslocamento Z'), Parametro('R', 'Número de passes')],
    exemplo: 'G73 U10. W5. R5\nG73 P100 Q200 U0.4 W0.1 F0.25',
    explicacaoExemplo: 'Desbaste de fundido: 5 passes copiando o perfil.', isG: true),

  CodigoItem(codigo: 'G75', nome: 'Ciclo de Canal/Ranhura — Torno Fanuc', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Ciclo de sangramento e ranhuras no torno. Executa canais automáticos.',
    descricaoCompleta: 'G75 executa ciclo de ranhuras (grooves) no torno. Pode fazer múltiplos canais igualmente espaçados. Muito usado para sangrias, retentores e canais de anel.',
    sintaxe: 'G75 R[recuo]\nG75 X[prof] Z[pos] P[passo X] Q[passo Z] F[av]',
    parametros: [Parametro('X', 'Diâmetro final do canal (profundidade)'), Parametro('Z', 'Posição Z final'), Parametro('P', 'Passo de incremento em X (μm)'), Parametro('Q', 'Espaçamento entre canais em Z (μm)'), Parametro('F', 'Avanço de sangramento')],
    exemplo: '; CANAL SIMPLES:\nG75 R0.5\nG75 X16. Z-25. P1000 Q0 F0.05\n;\n; MÚLTIPLOS CANAIS:\nG75 R0.5\nG75 X16. Z-35. P1000 Q5000 F0.05\n; Q5000 = 5mm entre canais',
    explicacaoExemplo: 'Canal único em X=16mm (prof.) em Z=-25mm. Para múltiplos: Q define espaçamento em μm.', isG: true),

  CodigoItem(codigo: 'G76', nome: 'Ciclo Automático de Rosca — Torno Fanuc', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Ciclo completo de rosca com passes automáticos. Mais prático que G92.',
    descricaoCompleta: 'G76 executa todos os passes de rosca automaticamente. Dois blocos definem o ciclo completo. Mais prático que G92 mas com menos controle por passe.',
    sintaxe: 'G76 P[m][r][a] Q[prof min] R[sobr]\nG76 X[diâm final] Z[compr] P[altura filete] Q[1º passe] F[passo]',
    parametros: [Parametro('P', '1º bloco: m=passes limpeza, r=chanfro, a=ângulo (60°=60)'), Parametro('X', 'Diâmetro final da rosca'), Parametro('Z', 'Comprimento'), Parametro('P 2ºbloco', 'Altura total do filete em μm'), Parametro('Q', '1º passe de profundidade em μm'), Parametro('F', 'Passo da rosca em mm')],
    exemplo: '; ROSCA M20×2.5\nG76 P021060 Q100 R0.1\nG76 X16.93 Z-40. P1534 Q300 F2.5\n;\n; P021060: 2 passes limpeza, chanfro r, ângulo 60°\n; P1534: altura filete M20×2.5 = 1534μm\n; Q300: 1º passe = 0.3mm',
    explicacaoExemplo: 'Ciclo completo rosca M20×2.5 — todos os passes automáticos!', isG: true),

  CodigoItem(codigo: 'G92', nome: 'Ciclo de Rosca Passe a Passe — Torno', categoria: 'Ciclos Torno', maquina: 'Torno CNC',
    descricao: 'Rosqueamento no torno — cada bloco = um passe. F = passo da rosca.',
    descricaoCompleta: 'G92 executa um passe de rosca por bloco. F é o passo da rosca. RPM FIXO obrigatório (G97). Passes progressivos do maior para menor diâmetro.',
    sintaxe: 'G92 X[diâm] Z[compr] F[passo]',
    parametros: [Parametro('X', 'Diâmetro do passe'), Parametro('Z', 'Comprimento da rosca'), Parametro('F', 'IGUAL AO PASSO da rosca em mm')],
    exemplo: 'G97 S400 M03  ; RPM FIXO!\nG92 X19.4 Z-40. F2.5\nG92 X18.9 Z-40. F2.5\nG92 X16.93 Z-40. F2.5  ; Final\nG92 X16.93 Z-40. F2.5  ; Limpeza',
    explicacaoExemplo: 'Passes progressivos de rosca — do maior para menor diâmetro.', isG: true),

  // ══════ TRANSFORMAÇÃO ══════
  CodigoItem(codigo: 'G68', nome: 'Rotação de Coordenadas', categoria: 'Transformação', maquina: 'Centro de Usinagem',
    descricao: 'Rotaciona o sistema de coordenadas em torno de um ponto.',
    descricaoCompleta: 'G68 rotaciona o sistema em torno de X,Y pelo ângulo R. Para features anguladas sem recalcular coordenadas.',
    sintaxe: 'G68 X[cx] Y[cy] R[ângulo]',
    parametros: [Parametro('X/Y', 'Centro de rotação'), Parametro('R', 'Ângulo graus (positivo=anti-horário)')],
    exemplo: 'G68 X0 Y0 R45.\nG01 X50. F200\nG69',
    explicacaoExemplo: 'Rotaciona 45° para usinar feature angulada.', isG: true),

  CodigoItem(codigo: 'G69', nome: 'Cancela Rotação', categoria: 'Transformação', maquina: 'Centro de Usinagem',
    descricao: 'Cancela G68 e retorna ao sistema original.',
    descricaoCompleta: 'G69 cancela rotação de coordenadas ativada pelo G68.',
    sintaxe: 'G69', parametros: [],
    exemplo: 'G68 X0 Y0 R30.\n; operações\nG69',
    explicacaoExemplo: 'Retorna ao sistema original após feature angulada.', isG: true),

  CodigoItem(codigo: 'G51', nome: 'Escala (Scaling)', categoria: 'Transformação', maquina: 'Centro de Usinagem',
    descricao: 'Aplica fator de escala ao programa.',
    descricaoCompleta: 'G51 amplia ou reduz coordenadas pelo fator P. P2000 = fator 2.0 (dobra tudo).',
    sintaxe: 'G51 X[cx] Y[cy] P[fator]',
    parametros: [Parametro('P', 'Fator × 1000 (P2000=2.0, P500=0.5)')],
    exemplo: 'G51 X0 Y0 P2000\nG01 X10. F200\nG50',
    explicacaoExemplo: 'P2000 = dobra todas as coordenadas.', isG: true),

  CodigoItem(codigo: 'G50', nome: 'Cancela Escala / Limita RPM', categoria: 'Transformação', maquina: 'Ambos',
    descricao: 'Cancela G51 ou define RPM máximo no torno com G96.',
    descricaoCompleta: 'G50: (1) Cancela escalonamento G51. (2) No torno com G96, G50 S[RPM] limita RPM máximo.',
    sintaxe: 'G50\nG50 S[RPM]  ; Limita RPM (torno)',
    parametros: [Parametro('S', 'RPM máximo (só torno com G96)')],
    exemplo: 'G96 S200\nG50 S3000',
    explicacaoExemplo: 'Protege spindle de RPM excessivo em diâmetros pequenos.', isG: true),

  CodigoItem(codigo: 'G51.1', nome: 'Espelhamento (Mirror Image)', categoria: 'Transformação', maquina: 'Centro de Usinagem',
    descricao: 'Espelha o programa em torno de um eixo — para peças simétricas.',
    descricaoCompleta: 'G51.1 ativa espelhamento. Permite usinar peças simétricas sem reprogramar. Cancela com G50.1.',
    sintaxe: 'G51.1 X[val]  ; Espelha em X\nG51.1 Y[val]  ; Espelha em Y',
    parametros: [Parametro('X', 'Posição do eixo espelho em X'), Parametro('Y', 'Posição do eixo espelho em Y')],
    exemplo: 'G51.1 X0\nG01 X-30. F200\nG50.1 X0',
    explicacaoExemplo: 'Espelha para usinar lado simétrico sem reprogramar.', isG: true),

  CodigoItem(codigo: 'G50.1', nome: 'Cancela Espelhamento', categoria: 'Transformação', maquina: 'Centro de Usinagem',
    descricao: 'Cancela G51.1 e restaura sistema original.',
    descricaoCompleta: 'G50.1 desativa o espelhamento do G51.1.',
    sintaxe: 'G50.1 X0', parametros: [],
    exemplo: 'G51.1 X0\n; operações\nG50.1 X0',
    explicacaoExemplo: 'Cancela espelhamento após operação simétrica.', isG: true),

  // ══════ MACRO ══════
  CodigoItem(codigo: 'G65', nome: 'Chamada de Macro (Custom Macro)', categoria: 'Macro', maquina: 'Ambos',
    descricao: 'Chama programa macro com passagem de parâmetros. Programação paramétrica.',
    descricaoCompleta: 'G65 chama macro O[número] passando argumentos A-Z que viram variáveis #1-#26. Permite loops, condicionais e cálculos dentro do CNC.',
    sintaxe: 'G65 P[prog] A[val] B[val] ... Z[val]',
    parametros: [Parametro('P', 'Número do programa macro'), Parametro('A-Z', 'Argumentos → variáveis #1-#26')],
    exemplo: 'G65 P9001 A20. B25. C4. I3. D15.',
    explicacaoExemplo: 'Chama O9001 com parâmetros para operação parametrizada.', isG: true),
];

// ─────────────────────────────────────────
// CÓDIGOS M — COMPLETO
// ─────────────────────────────────────────
const codigosM = [
  CodigoItem(codigo: 'M00', nome: 'Parada de Programa', categoria: 'Controle', maquina: 'Ambos',
    descricao: 'Para o programa e aguarda CYCLE START. Spindle e fluido param.',
    descricaoCompleta: 'M00 interrompe completamente o programa. Operador pode medir, verificar, limpar. Continua ao pressionar CYCLE START.',
    sintaxe: 'M00', parametros: [],
    exemplo: 'G01 Z-5. F100\nM00\nG01 Z-10.',
    explicacaoExemplo: 'Para para verificação entre operações.', isG: false),

  CodigoItem(codigo: 'M01', nome: 'Parada Opcional', categoria: 'Controle', maquina: 'Ambos',
    descricao: 'Para apenas se a chave Optional Stop estiver ligada no painel.',
    descricaoCompleta: 'M01 é condicional à chave do painel. Em setup: para. Em produção série: ignora automaticamente.',
    sintaxe: 'M01', parametros: [],
    exemplo: 'G01 X50. F200\nM01',
    explicacaoExemplo: 'Flexível — controla pelo painel se para ou não.', isG: false),

  CodigoItem(codigo: 'M02', nome: 'Fim de Programa', categoria: 'Controle', maquina: 'Ambos',
    descricao: 'Encerra o programa. Geralmente não rebobina o cursor.',
    descricaoCompleta: 'M02 encerra o programa. Diferente do M30, geralmente não volta o cursor ao início.',
    sintaxe: 'M02', parametros: [],
    exemplo: 'G28 Z0\nM05\nM02',
    explicacaoExemplo: 'Menos usado que M30 — não rebobina.', isG: false),

  CodigoItem(codigo: 'M03', nome: 'Liga Spindle Horário (CW)', categoria: 'Spindle', maquina: 'Ambos',
    descricao: 'Liga spindle sentido horário. Padrão para fresas e brocas.',
    descricaoCompleta: 'M03 liga spindle CW. Sentido padrão para fresas, brocas e maioria das ferramentas. Sempre programar S antes do M03 ou no mesmo bloco.',
    sintaxe: 'S[RPM] M03',
    parametros: [Parametro('S', 'Rotação em RPM')],
    exemplo: 'S2000 M03\nG01 Z-3. F200',
    explicacaoExemplo: 'Liga 2000 RPM horário e inicia corte.',
    dicaProfissional: 'Sempre programe S e M03 no mesmo bloco ou S antes. Aguarde alguns segundos após M03 antes do primeiro corte para o spindle atingir a velocidade nominal — especialmente importante em altas rotações (acima de 10.000 RPM).',
    diagramaTipo: 'spindle_cw',
    isG: false),

  CodigoItem(codigo: 'M04', nome: 'Liga Spindle Anti-horário (CCW)', categoria: 'Spindle', maquina: 'Ambos',
    descricao: 'Liga spindle sentido anti-horário.',
    descricaoCompleta: 'M04 liga spindle CCW. Para rosca esquerda, rosqueamento reverso e ferramentas especiais.',
    sintaxe: 'S[RPM] M04',
    parametros: [Parametro('S', 'RPM')],
    exemplo: 'S800 M04',
    explicacaoExemplo: 'Liga anti-horário para ferramenta especial.',
    dicaProfissional: 'M04 é usado para: rosca esquerda (M84 anti-horária), machos com reversão interna, e ferramentas de torneamento com pastilhas configuradas para CCW. Confirme no catálogo da ferramenta qual sentido é correto.',
    diagramaTipo: 'spindle_ccw',
    isG: false),

  CodigoItem(codigo: 'M05', nome: 'Para Spindle', categoria: 'Spindle', maquina: 'Ambos',
    descricao: 'Para a rotação do spindle completamente.',
    descricaoCompleta: 'M05 para o spindle. Aguarda parada completa antes do próximo bloco. Usar antes de M06.',
    sintaxe: 'M05', parametros: [],
    exemplo: 'G00 Z50.\nM05\nM06 T02',
    explicacaoExemplo: 'Para spindle antes da troca de ferramenta.',
    dicaProfissional: 'Em muitas máquinas, M06 já inclui M05 automaticamente. Mas é boa prática programar M05 explicitamente antes de M06 para garantir parada completa. O tempo de parada depende da inércia do spindle — spindles de alta rotação demoram mais.',
    isG: false),

  CodigoItem(codigo: 'M06', nome: 'Troca Automática de Ferramenta (ATC)', categoria: 'Ferramenta', maquina: 'Centro de Usinagem',
    descricao: 'Executa troca automática de ferramenta. Sempre retorne ao zero antes.',
    descricaoCompleta: 'M06 aciona o ATC. Sempre retorne ao ponto seguro (G28 Z0) e pare o spindle (M05) antes. É boa prática pré-selecionar a próxima ferramenta (T) com antecedência para reduzir tempo de ciclo.',
    sintaxe: 'T[n] M06',
    parametros: [Parametro('T', 'Número da ferramenta (T01-T60+)')],
    exemplo: 'G28 Z0\nT02 M06\nS2000 M03\nG43 H02 Z100.',
    explicacaoExemplo: 'Troca T2, liga spindle e ativa compensação H02.',
    dicaProfissional: 'Para reduzir tempo de ciclo: pré-selecione a PRÓXIMA ferramenta no final de cada operação. Exemplo: ao terminar com T01, programe T02 antes do G28. Assim o carrossel já posiciona T02 enquanto a máquina ainda está usinando com T01.',
    diagramaTipo: 'troca_ferramenta',
    isG: false),

  CodigoItem(codigo: 'M07', nome: 'Liga Refrigeração de Névoa', categoria: 'Refrigeração', maquina: 'Ambos',
    descricao: 'Liga sistema de névoa (mist coolant). Para alumínio e plásticos.',
    descricaoCompleta: 'M07 ativa névoa (ar + fluido). Menos fluido que M08.',
    sintaxe: 'M07', parametros: [],
    exemplo: 'S2000 M03\nM07',
    explicacaoExemplo: 'Névoa para fresamento de alumínio.',
    dicaProfissional: 'Névoa (M07) é ideal para alumínio, plástico e materiais que não devem molhar (ex: grafite). Gera vapor — use EPI (máscara) e ventilação. Para aço e inox prefira sempre M08 (flood) — a névoa não resfria suficientemente em cortes pesados.',
    isG: false),

  CodigoItem(codigo: 'M08', nome: 'Liga Refrigeração Flood', categoria: 'Refrigeração', maquina: 'Ambos',
    descricao: 'Liga fluido de corte abundante. Obrigatório para aço e inox.',
    descricaoCompleta: 'M08 ativa flood coolant. Resfria ferramenta e peça, remove cavaco. Obrigatório para aço, inox e materiais difíceis.',
    sintaxe: 'M08', parametros: [],
    exemplo: 'S1500 M03\nM08',
    explicacaoExemplo: 'Liga fluido antes de cortar aço.',
    dicaProfissional: 'Ligue M08 ANTES de iniciar o corte, não durante. Temperatura súbita em ferramenta quente pode gerar micro-trincas. Verifique concentração do fluido semanalmente (ideal 6-8% em refratômetro) — fluido fraco não refrigera e prolifera bactérias.',
    diagramaTipo: 'refrigeracao',
    isG: false),

  CodigoItem(codigo: 'M09', nome: 'Desliga Refrigeração', categoria: 'Refrigeração', maquina: 'Ambos',
    descricao: 'Desliga todos os sistemas de refrigeração (M07 e M08).',
    descricaoCompleta: 'M09 para toda refrigeração.',
    sintaxe: 'M09', parametros: [],
    exemplo: 'G00 Z50.\nM09\nM05\nM30',
    explicacaoExemplo: 'Sequência de finalização profissional.', isG: false),

  CodigoItem(codigo: 'M10', nome: 'Fecha Chuck (Torno)', categoria: 'Torno', maquina: 'Torno CNC',
    descricao: 'Fecha e trava o mandril do torno hidraulicamente.',
    descricaoCompleta: 'M10 aciona o sistema hidráulico para fechar e travar o mandril. Para automação com alimentador de barras.',
    sintaxe: 'M10', parametros: [],
    exemplo: 'M10\nS1000 M03',
    explicacaoExemplo: 'Fecha mandril antes de tornear.', isG: false),

  CodigoItem(codigo: 'M11', nome: 'Abre Chuck (Torno)', categoria: 'Torno', maquina: 'Torno CNC',
    descricao: 'Abre o mandril do torno.',
    descricaoCompleta: 'M11 libera o mandril. Para ejetar peça ou alimentação automática.',
    sintaxe: 'M11', parametros: [],
    exemplo: 'M05\nM11',
    explicacaoExemplo: 'Abre mandril após finalizar peça.', isG: false),

  CodigoItem(codigo: 'M12', nome: 'Avança Contra-ponta', categoria: 'Torno', maquina: 'Torno CNC',
    descricao: 'Avança a contra-ponta para apoiar peças longas.',
    descricaoCompleta: 'M12 avança a contra-ponta hidráulica. Para suporte axial em eixos longos.',
    sintaxe: 'M12', parametros: [],
    exemplo: 'M12\nS500 M03',
    explicacaoExemplo: 'Suporte axial antes de tornear eixo longo.', isG: false),

  CodigoItem(codigo: 'M13', nome: 'Recua Contra-ponta', categoria: 'Torno', maquina: 'Torno CNC',
    descricao: 'Recua a contra-ponta para liberar a peça.',
    descricaoCompleta: 'M13 recua a contra-ponta após o torneamento.',
    sintaxe: 'M13', parametros: [],
    exemplo: 'M05\nM13\nM11',
    explicacaoExemplo: 'Libera peça: para spindle, recua contra-ponta, abre chuck.', isG: false),

  CodigoItem(codigo: 'M19', nome: 'Parada Orientada do Spindle', categoria: 'Spindle', maquina: 'Ambos',
    descricao: 'Para o spindle em posição angular específica. Essencial antes do G76.',
    descricaoCompleta: 'M19 para spindle em posição angular pré-definida. Necessário antes de G76 (mandrilamento fino).',
    sintaxe: 'M19', parametros: [],
    exemplo: 'M19\nG76 X30. Y20. Z-15. R2. Q100 F50',
    explicacaoExemplo: 'Orienta spindle antes do mandrilamento fino.', isG: false),

  CodigoItem(codigo: 'M21', nome: 'Espelhamento em X', categoria: 'Espelhamento', maquina: 'Centro de Usinagem',
    descricao: 'Ativa espelhamento no eixo X para peças simétricas.',
    descricaoCompleta: 'M21 inverte todos os movimentos X. Cancela com M23.',
    sintaxe: 'M21', parametros: [],
    exemplo: 'M21\nG01 X-30. F200\nM23',
    explicacaoExemplo: 'Usina lado simétrico em X sem reprogramar.', isG: false),

  CodigoItem(codigo: 'M22', nome: 'Espelhamento em Y', categoria: 'Espelhamento', maquina: 'Centro de Usinagem',
    descricao: 'Ativa espelhamento no eixo Y.',
    descricaoCompleta: 'M22 inverte todos os movimentos Y. Cancela com M24.',
    sintaxe: 'M22', parametros: [],
    exemplo: 'M22\nG01 Y-30. F200\nM24',
    explicacaoExemplo: 'Usina lado simétrico em Y.', isG: false),

  CodigoItem(codigo: 'M23', nome: 'Cancela Espelhamento X', categoria: 'Espelhamento', maquina: 'Centro de Usinagem',
    descricao: 'Desativa espelhamento em X (M21).',
    descricaoCompleta: 'M23 cancela M21.',
    sintaxe: 'M23', parametros: [],
    exemplo: 'M21\nG01 X-50. F200\nM23',
    explicacaoExemplo: 'Cancela espelhamento X.', isG: false),

  CodigoItem(codigo: 'M24', nome: 'Cancela Espelhamento Y', categoria: 'Espelhamento', maquina: 'Centro de Usinagem',
    descricao: 'Desativa espelhamento em Y (M22).',
    descricaoCompleta: 'M24 cancela M22.',
    sintaxe: 'M24', parametros: [],
    exemplo: 'M22\nG01 Y-50. F200\nM24',
    explicacaoExemplo: 'Cancela espelhamento Y.', isG: false),

  CodigoItem(codigo: 'M30', nome: 'Fim e Rebobina Programa', categoria: 'Controle', maquina: 'Ambos',
    descricao: 'Encerra e volta cursor ao início. O código de fim mais usado no mundo.',
    descricaoCompleta: 'M30 encerra, para spindle e refrigeração e reposiciona o cursor no início para a próxima peça.',
    sintaxe: 'M30', parametros: [],
    exemplo: 'G28 Z0\nG28 X0 Y0\nM09\nM05\nM30',
    explicacaoExemplo: 'Sequência profissional — padrão mundial.',
    dicaProfissional: 'A sequência correta antes do M30 é sempre: (1) G28 Z0 — sobe Z. (2) G28 X0 Y0 — retorna X,Y. (3) M09 — desliga fluido. (4) M05 — para spindle. (5) M30. Nunca pule essas etapas em programas de produção.',
    isG: false),

  CodigoItem(codigo: 'M41', nome: 'Gama de Velocidade Baixa', categoria: 'Spindle', maquina: 'Ambos',
    descricao: 'Seleciona gama baixa da caixa de velocidades — alto torque.',
    descricaoCompleta: 'M41 seleciona gama 1 (baixa). Para rosqueamento, furação grande e operações de alto torque.',
    sintaxe: 'M41', parametros: [],
    exemplo: 'M41\nS200 M03',
    explicacaoExemplo: 'Gama baixa para rosqueamento com macho grande.', isG: false),

  CodigoItem(codigo: 'M42', nome: 'Gama de Velocidade Alta', categoria: 'Spindle', maquina: 'Ambos',
    descricao: 'Seleciona gama alta — alta rotação, menor torque.',
    descricaoCompleta: 'M42 seleciona gama 2 (alta). Para acabamento e fresas pequenas em alta rotação.',
    sintaxe: 'M42', parametros: [],
    exemplo: 'M42\nS8000 M03',
    explicacaoExemplo: 'Gama alta para fresa pequena em alta rotação.', isG: false),

  CodigoItem(codigo: 'M48', nome: 'Habilita Override', categoria: 'Controle', maquina: 'Ambos',
    descricao: 'Reativa os botões de override de avanço e spindle do painel.',
    descricaoCompleta: 'M48 habilita os overrides do painel. Usar após M49.',
    sintaxe: 'M48', parametros: [],
    exemplo: 'M49\nG84 Z-20. F450\nG80\nM48',
    explicacaoExemplo: 'Reativa overrides após rosqueamento.', isG: false),

  CodigoItem(codigo: 'M49', nome: 'Desabilita Override', categoria: 'Controle', maquina: 'Ambos',
    descricao: 'Bloqueia overrides. Obrigatório em rosqueamento.',
    descricaoCompleta: 'M49 bloqueia todos os overrides. Para rosqueamento onde parâmetros não podem ser alterados.',
    sintaxe: 'M49', parametros: [],
    exemplo: 'M49\nG84 X20. Z-20. F450\nM48',
    explicacaoExemplo: 'Bloqueia durante rosqueamento — evita quebrar macho.', isG: false),

  CodigoItem(codigo: 'M50', nome: 'Liga Fluido pelo Furo da Ferramenta', categoria: 'Refrigeração', maquina: 'Centro de Usinagem',
    descricao: 'Liga fluido de alta pressão pelo interior da ferramenta.',
    descricaoCompleta: 'M50 ativa fluido pelo centro do spindle e ferramenta. Para furos profundos e materiais difíceis como inox e titânio.',
    sintaxe: 'M50', parametros: [],
    exemplo: 'M50\nG83 X20. Z-60. R2. Q8. F60\nG80\nM51',
    explicacaoExemplo: 'Fluido interno para furo profundo — evacua cavaco do fundo.', isG: false),

  CodigoItem(codigo: 'M51', nome: 'Desliga Fluido pelo Furo', categoria: 'Refrigeração', maquina: 'Centro de Usinagem',
    descricao: 'Desliga fluido de alta pressão pelo interior (M50).',
    descricaoCompleta: 'M51 desativa o fluido através do spindle ativado por M50.',
    sintaxe: 'M51', parametros: [],
    exemplo: 'M50\nG83 X20. Z-60. R2. Q8. F60\nM51',
    explicacaoExemplo: 'Desliga fluido pelo fuso após furação profunda.', isG: false),

  CodigoItem(codigo: 'M60', nome: 'Troca de Palete (APC)', categoria: 'Automação', maquina: 'Centro de Usinagem',
    descricao: 'Executa troca automática de palete para produção contínua.',
    descricaoCompleta: 'M60 aciona o APC. Palete usinado sai e próximo com peça bruta entra. Produção desassistida.',
    sintaxe: 'M60', parametros: [],
    exemplo: 'G28 Z0\nG28 X0 Y0\nM60\nG54',
    explicacaoExemplo: 'Troca palete para produção automática não-stop.', isG: false),

  CodigoItem(codigo: 'M98', nome: 'Chamada de Subprograma', categoria: 'Subprograma', maquina: 'Ambos',
    descricao: 'Chama um subprograma externo pelo número P. L define repetições.',
    descricaoCompleta: 'M98 chama O[número] e executa. L define quantas vezes. Retorna ao próximo bloco após M98.',
    sintaxe: 'M98 P[número] L[repetições]',
    parametros: [Parametro('P', 'Número do subprograma'), Parametro('L', 'Repetições (padrão: 1)')],
    exemplo: 'M98 P1001\nM98 P1001 L5',
    explicacaoExemplo: 'Chama O1001 uma vez ou repete 5 vezes.', isG: false),

  CodigoItem(codigo: 'M99', nome: 'Fim de Subprograma / Retorno', categoria: 'Subprograma', maquina: 'Ambos',
    descricao: 'Retorna do subprograma ao programa principal.',
    descricaoCompleta: 'M99 marca fim do subprograma e retorna. No programa principal: reinicia do início (loop).',
    sintaxe: 'M99', parametros: [],
    exemplo: '; Sub O1001\nG81 X0 Y0 Z-15. R2. F100\nX20.\nG80\nM99',
    explicacaoExemplo: 'M99 retorna ao programa principal.', isG: false),
];

// ─────────────────────────────────────────
// ALARMES FANUC
// ─────────────────────────────────────────
const alarmesFanuc = [
  AlarmeItem(codigo: 'AL.010', titulo: 'Improper G-code',
    descricao: 'Código G inválido ou não suportado nesta versão.',
    descricaoCompleta: 'CNC encontrou código G que não existe ou não é suportado.',
    gravidade: 'MÉDIO', categoria: 'Programação',
    causas: ['Código G incorreto', 'Versão Fanuc não suporta', 'Opção não instalada'],
    solucoes: ['Verificar número do código', 'Consultar manual da versão', 'Verificar opções habilitadas'],
    atencao: null),
  AlarmeItem(codigo: 'AL.085', titulo: 'Communication Error RS-232',
    descricao: 'Erro de comunicação serial durante transferência de programa.',
    descricaoCompleta: 'Falha na comunicação RS-232 entre CNC e computador DNC.',
    gravidade: 'MÉDIO', categoria: 'Comunicação',
    causas: ['Parâmetros incompatíveis (baud rate)', 'Cabo com defeito', 'Software DNC mal configurado'],
    solucoes: ['Conferir P101/P103 (9600 baud, 7 bits, paridade par)', 'Verificar cabo RS-232', 'Reconfigurar software DNC'],
    atencao: null),
  AlarmeItem(codigo: 'AL.300', titulo: 'APC Alarm — Request Zero Return',
    descricao: 'Encoder absoluto perdeu referência.',
    descricaoCompleta: 'Encoder absoluto perdeu referência após troca de bateria ou falta de energia.',
    gravidade: 'MÉDIO', categoria: 'Referência',
    causas: ['Bateria descarregada', 'Falta de energia >72h', 'Substituição do encoder'],
    solucoes: ['ZERO RETURN: Z→X→Y', 'Verificar bateria (≥3V)', 'Substituir CR17335 3V'],
    atencao: null),
  AlarmeItem(codigo: 'AL.350', titulo: 'APC Alarm — Battery Voltage Low',
    descricao: 'Bateria do encoder absoluto com tensão baixa — substituir urgente.',
    descricaoCompleta: 'Tensão da bateria abaixo do mínimo. Substituir antes de perder referência.',
    gravidade: 'ALTO', categoria: 'Manutenção',
    causas: ['Bateria descarregada (vida: 2-3 anos)'],
    solucoes: ['Substituir CR17335 3V', 'Trocar com máquina LIGADA', 'Preventivo a cada 2 anos'],
    atencao: 'Trocar com máquina ENERGIZADA. Desligar apaga a referência absoluta.'),
  AlarmeItem(codigo: 'AL.401', titulo: 'Servo Alarm — VRDY Off',
    descricao: 'Drive servo não está pronto — sinal VRDY ausente.',
    descricaoCompleta: 'Amplificador servo não enviou sinal VRDY ao CNC.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Alarme no amplificador', 'Emergência bloqueando enable', 'Alimentação 200V interrompida', 'Cabo FSSB com falha'],
    solucoes: ['Verificar LEDs do amplificador', 'Liberar emergência', 'Verificar tensão 200V', 'Inspecionar cabo fibra óptica'],
    atencao: 'Não resetar repetidamente sem identificar causa.'),
  AlarmeItem(codigo: 'AL.410', titulo: 'Servo Axis — Speed Error Overflow',
    descricao: 'Erro de velocidade no servo — diferença real vs. comandada.',
    descricaoCompleta: 'Diferença entre velocidade real e comandada ultrapassou o limite.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Sobrecarga mecânica', 'Ganho P1825/P1826 incorreto', 'Encoder intermitente', 'Motor com defeito'],
    solucoes: ['Verificar obstrução mecânica', 'Conferir P1825/P1826', 'Inspecionar encoder', 'Verificar tensão DC (270-340V)'],
    atencao: 'NÃO mover com alarme ativo. Verificar colisão antes de religar.'),
  AlarmeItem(codigo: 'AL.414', titulo: 'Servo Axis — Detect Error Overflow',
    descricao: 'Erro de posição acima do limite configurado no P1828.',
    descricaoCompleta: 'Diferença entre posição comandada e real excedeu P1828.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['P1828 restritivo', 'Avanço além da capacidade', 'Encoder com falha', 'Correia com folga'],
    solucoes: ['P1828 típico: 20000-50000', 'Reduzir avanço F', 'Verificar encoder DGN 300', 'ZERO RETURN após resolver'],
    atencao: 'Execute ZERO RETURN após solucionar.'),
  AlarmeItem(codigo: 'AL.500', titulo: 'Stroke Limit — Over Travel',
    descricao: 'Eixo atingiu o limite de software.',
    descricaoCompleta: 'Eixo tentou ultrapassar o limite de curso definido.',
    gravidade: 'ALTO', categoria: 'Limite de Curso',
    causas: ['Zero-peça incorreto', 'Coordenada além do curso', 'P1320/P1321 incorretos'],
    solucoes: ['Mover na direção contrária (JOG/MPG)', 'Corrigir zero-peça G54-G59', 'Revisar coordenadas máximas'],
    atencao: 'NUNCA forçar mecanicamente.'),
  AlarmeItem(codigo: 'AL.700', titulo: 'Overheat — Control Unit',
    descricao: 'Superaquecimento na unidade de controle — temperatura >55°C.',
    descricaoCompleta: 'Temperatura interna do gabinete ultrapassou 55°C.',
    gravidade: 'CRÍTICO', categoria: 'Temperatura',
    causas: ['Filtro de ar entupido', 'Ventilador parado', 'Temperatura ambiente >35°C', 'Ar condicionado com defeito'],
    solucoes: ['Desligar e aguardar 30min', 'Limpar filtros mensalmente', 'Verificar ventiladores', 'Ar condicionado: temp. interna <40°C'],
    atencao: 'NÃO religar até normalizar. Custo pode ultrapassar R\$ 30.000.'),
  AlarmeItem(codigo: 'AL.910', titulo: 'RAM Parity Error',
    descricao: 'Erro de paridade na memória RAM do CNC.',
    descricaoCompleta: 'Erro detectado na RAM — pode ser hardware ou interferência eletromagnética.',
    gravidade: 'CRÍTICO', categoria: 'Sistema',
    causas: ['Bateria de backup descarregada', 'Interferência eletromagnética', 'Placa RAM com defeito'],
    solucoes: ['BACKUP COMPLETO primeiro!', 'Verificar bateria de backup', 'CLEAR de memória (só com backup)', 'Recarregar parâmetros'],
    atencao: 'CLEAR apaga TUDO. Backup obrigatório antes.'),
];

// ─────────────────────────────────────────
// ALARMES SIEMENS
// ─────────────────────────────────────────
const alarmesSiemens = [
  AlarmeItem(codigo: '25050', titulo: 'Encoder Monitoring — Speed Difference',
    descricao: 'Diferença de velocidade entre encoders acima do MD36300.',
    descricaoCompleta: 'Diferença entre encoder do motor e régua linear ultrapassou MD36300.',
    gravidade: 'CRÍTICO', categoria: 'Encoder',
    causas: ['Folga mecânica', 'Régua intermitente', 'MD36300 restritivo', 'Cabo com interferência'],
    solucoes: ['Ajustar MD36300/36302', 'Limpar e inspecionar régua', 'Verificar blindagem dos cabos'],
    atencao: null),
  AlarmeItem(codigo: '21612', titulo: 'Drive Fault — DC Link Voltage Too Low',
    descricao: 'Tensão DC do drive SIMODRIVE/S120 abaixo do mínimo.',
    descricaoCompleta: 'Tensão DC abaixo do mínimo (600V DC para 380V AC).',
    gravidade: 'CRÍTICO', categoria: 'Drive',
    causas: ['Rede abaixo de 380V', 'Fusíveis queimados', 'Retificador com defeito', 'Conexão solta'],
    solucoes: ['Medir tensão trifásica (380-400V ±10%)', 'Verificar fusíveis', 'Medir DC nos terminais P e N'],
    atencao: 'NÃO tocar DC sem aguardar 5min. 600V DC é fatal.'),
  AlarmeItem(codigo: '21614', titulo: 'Drive Fault — DC Link Voltage Too High',
    descricao: 'Sobretensão no barramento DC do drive.',
    descricaoCompleta: 'Tensão DC excessiva. Problema no resistor de frenagem ou desaceleração muito rápida.',
    gravidade: 'CRÍTICO', categoria: 'Drive',
    causas: ['Resistor de frenagem com defeito', 'Desaceleração muito rápida', 'Módulo chopper com falha'],
    solucoes: ['Verificar resistor de frenagem', 'Aumentar tempo de desaceleração', 'Verificar módulo chopper'],
    atencao: 'Aguardar descarga dos capacitores antes de manusear.'),
  AlarmeItem(codigo: '380500', titulo: 'PLC Stop — Emergency Stop Active',
    descricao: 'Emergência ativada — CLP em STOP.',
    descricaoCompleta: 'Circuito de emergência ativado. CLP em STOP, todos os acionamentos desabilitados.',
    gravidade: 'ALTO', categoria: 'Segurança',
    causas: ['Emergência pressionada', 'Porta aberta', 'Pressão hidráulica/pneumática baixa', 'Relé de segurança com falha'],
    solucoes: ['Liberar botão de emergência', 'Fechar todas as portas', 'Verificar pressões', 'RESET → SINUMERIK RESET'],
    atencao: null),
  AlarmeItem(codigo: '26050', titulo: 'Contour Monitoring — Error Too Large',
    descricao: 'Erro de contorno acima do limite MD36400.',
    descricaoCompleta: 'Erro de seguimento de contorno ultrapassou MD36400.',
    gravidade: 'ALTO', categoria: 'Contorno',
    causas: ['Avanço muito alto', 'MD36400 restritivo', 'Guias sem lubrificação', 'Aceleração brusca'],
    solucoes: ['Reduzir override 50%', 'Lubrificar guias', 'Ajustar MD36400', 'Usar G64 com tolerância'],
    atencao: null),
  AlarmeItem(codigo: '25000', titulo: 'Encoder Fault — Signal Level Too Low',
    descricao: 'Sinal do encoder abaixo do nível mínimo.',
    descricaoCompleta: 'Sinal sin/cos ou TTL do encoder abaixo do mínimo. Encoder danificado ou problema no cabo.',
    gravidade: 'ALTO', categoria: 'Encoder',
    causas: ['Encoder sujo ou danificado', 'Cabo com par partido', 'Conector oxidado'],
    solucoes: ['Limpar cabeça leitora', 'Verificar continuidade do cabo', 'Limpar conectores', 'Substituir encoder se dano confirmado'],
    atencao: null),
];

// ─────────────────────────────────────────
// ALARMES HAAS
// ─────────────────────────────────────────
const alarmesHaas = [
  AlarmeItem(codigo: '101', titulo: 'SERVO ERROR — X Axis Overload',
    descricao: 'Sobrecarga no servo do eixo X.',
    descricaoCompleta: 'Corrente do servo X excedeu o limite. Proteção térmica desligou o drive.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Avanço excessivo', 'Ferramenta gasta', 'Colisão', 'Guias sem lubrificação'],
    solucoes: ['Aguardar 10min resfriamento', 'Verificar obstrução', 'Reduzir override 25%', 'Verificar ferramenta'],
    atencao: 'Se retornar imediatamente: chamar técnico HAAS.'),
  AlarmeItem(codigo: '119', titulo: 'SPINDLE OVERLOAD',
    descricao: 'Sobrecarga no motor do spindle.',
    descricaoCompleta: 'Corrente do spindle excedeu o limite. Remoção de material excessiva.',
    gravidade: 'ALTO', categoria: 'Spindle',
    causas: ['Corte excessivo', 'Ferramenta gasta', 'RPM baixo para o diâmetro'],
    solucoes: ['Reduzir override 50%', 'Verificar ferramenta', 'Aumentar RPM ou reduzir fz'],
    atencao: null),
  AlarmeItem(codigo: '138', titulo: 'DOOR OPEN — Cannot Start Cycle',
    descricao: 'Porta aberta — impossível iniciar ciclo automático.',
    descricaoCompleta: 'Porta de proteção aberta ou sensor não detecta fechamento.',
    gravidade: 'MÉDIO', categoria: 'Segurança',
    causas: ['Porta aberta', 'Sensor desalinhado', 'Imã deslocado', 'Cabo do sensor com falha'],
    solucoes: ['Verificar fechamento completo', 'Alinhar sensor/imã', 'Testar I/O no diagnóstico'],
    atencao: null),
  AlarmeItem(codigo: '263', titulo: 'LOW AIR PRESSURE — Below 85 PSI',
    descricao: 'Pressão de ar abaixo do mínimo requerido.',
    descricaoCompleta: 'Ar comprimido abaixo de 85 PSI. Essencial para spindle e ATC.',
    gravidade: 'ALTO', categoria: 'Pneumático',
    causas: ['Compressor desligado', 'Vazamento na linha', 'Filtro entupido', 'Regulador mal ajustado'],
    solucoes: ['Verificar compressor', 'Medir pressão (mín. 85 PSI)', 'Drenar filtro regulador', 'Ajustar 90-100 PSI'],
    atencao: 'Pressão baixa pode causar queda de ferramenta.'),
  AlarmeItem(codigo: '316', titulo: 'TOOL CHANGER ARM — Home Not Found',
    descricao: 'Braço do trocador não encontrou posição HOME.',
    descricaoCompleta: 'Braço do ATC não retornou à posição de repouso.',
    gravidade: 'CRÍTICO', categoria: 'Trocador',
    causas: ['Ferramenta presa no braço', 'Sensor HOME com defeito', 'Pressão insuficiente', 'Objeto no carrossel'],
    solucoes: ['DESLIGAR antes de intervir', 'Verificar ferramenta presa', 'Verificar pressão (85 PSI)', 'RESET → ATC INIT'],
    atencao: 'NUNCA colocar mãos no ATC com máquina ligada.'),
  AlarmeItem(codigo: '399', titulo: 'M-CODE NOT RECOGNIZED',
    descricao: 'Código M não reconhecido pelo CNC HAAS.',
    descricaoCompleta: 'Programa contém código M que não existe ou opção não instalada.',
    gravidade: 'MÉDIO', categoria: 'Programação',
    causas: ['Código M incorreto', 'Opção não instalada (4º eixo)', 'Código de outro fabricante'],
    solucoes: ['Verificar código M no manual HAAS', 'Confirmar se opção está instalada', 'Corrigir ou remover código'],
    atencao: null),
  AlarmeItem(codigo: '401', titulo: 'SERVO — HIGH FOLLOWING ERROR',
    descricao: 'Erro de seguimento excessivo em eixo HAAS.',
    descricaoCompleta: 'Erro de posição de um eixo excedeu o limite configurado.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Avanço muito alto', 'Sobrecarga mecânica', 'Problema no encoder'],
    solucoes: ['Reduzir override', 'Verificar obstrução mecânica', 'ZERO RETURN após resolver'],
    atencao: 'Execute ZERO RETURN após solucionar.'),
];

// ─────────────────────────────────────────
// ALARMES MAZAK
// ─────────────────────────────────────────
const alarmesMazak = [
  AlarmeItem(codigo: 'A.001', titulo: 'Emergency Stop',
    descricao: 'Parada de emergência acionada no Mazatrol.',
    descricaoCompleta: 'Circuito de emergência ativado.',
    gravidade: 'ALTO', categoria: 'Segurança',
    causas: ['Botão de emergência', 'Porta aberta', 'Pressão insuficiente'],
    solucoes: ['Liberar emergência', 'Fechar portas', 'Verificar pressões', 'Pressionar RESET'],
    atencao: null),
  AlarmeItem(codigo: 'A.010', titulo: 'Servo Alarm — Following Error',
    descricao: 'Erro de seguimento excessivo no eixo Mazak.',
    descricaoCompleta: 'Erro de posição ultrapassou o limite no Mazatrol.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Colisão mecânica', 'Parâmetro restritivo', 'Encoder com falha'],
    solucoes: ['Verificar obstrução', 'Reduzir avanço', 'ZERO RETURN após resolver'],
    atencao: null),
  AlarmeItem(codigo: 'A.200', titulo: 'ATC Alarm — Tool Change Error',
    descricao: 'Erro durante troca automática de ferramenta.',
    descricaoCompleta: 'ATC não completou o ciclo de troca corretamente.',
    gravidade: 'CRÍTICO', categoria: 'Trocador',
    causas: ['Ferramenta presa', 'Pressão insuficiente', 'Sensor com defeito'],
    solucoes: ['DESLIGAR antes de intervir', 'Verificar ferramenta', 'ATC RESET no Mazatrol'],
    atencao: 'Máquina DESLIGADA antes de intervenção manual.'),
  AlarmeItem(codigo: 'A.300', titulo: 'Hydraulic Pressure Low',
    descricao: 'Pressão hidráulica abaixo do mínimo.',
    descricaoCompleta: 'Sistema hidráulico fora da pressão mínima requerida.',
    gravidade: 'ALTO', categoria: 'Hidráulica',
    causas: ['Bomba desligada', 'Nível baixo', 'Filtro entupido'],
    solucoes: ['Verificar bomba', 'Verificar nível óleo', 'Trocar filtro (500h)', 'Pressão: 4.5-5.5 MPa'],
    atencao: 'Não operar com pressão baixa.'),
  AlarmeItem(codigo: 'B.010', titulo: 'Tool Life Expired',
    descricao: 'Vida útil da ferramenta atingiu o limite programado.',
    descricaoCompleta: 'Gerenciamento de vida indica ferramenta no limite.',
    gravidade: 'MÉDIO', categoria: 'Ferramenta',
    causas: ['Limite de vida atingido', 'Contador não resetado'],
    solucoes: ['Substituir ferramenta', 'Resetar contador no Mazatrol'],
    atencao: null),
];

// ─────────────────────────────────────────
// ALARMES MITSUBISHI
// ─────────────────────────────────────────
const alarmesMitsubishi = [
  AlarmeItem(codigo: 'E01', titulo: 'Emergency Stop Input',
    descricao: 'Sinal de emergência recebido pelo CNC Mitsubishi M70/M80.',
    descricaoCompleta: 'CNC M70/M80 recebeu sinal de emergência.',
    gravidade: 'ALTO', categoria: 'Segurança',
    causas: ['Botão de emergência', 'Sinal EMG do CLP', 'Falha no circuito'],
    solucoes: ['Liberar botão', 'Verificar CLP', 'RESET após liberar'],
    atencao: null),
  AlarmeItem(codigo: 'S01', titulo: 'Servo Alarm — Current Control',
    descricao: 'Problema no controle de corrente do drive MDS.',
    descricaoCompleta: 'Drive MDS detectou problema no controle de corrente do motor.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Drive com defeito', 'Motor com curto entre fases', 'Temperatura excessiva', 'Cabo de potência com falha'],
    solucoes: ['Verificar temperatura drive (máx. 55°C)', 'Medir resistência do motor', 'Verificar isolamento do cabo'],
    atencao: 'Medir motor com máquina DESLIGADA.'),
  AlarmeItem(codigo: 'S02', titulo: 'Servo Alarm — Overcurrent',
    descricao: 'Sobrecorrente detectada no drive servo.',
    descricaoCompleta: 'Corrente no motor servo excedeu o limite de proteção.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Sobrecarga mecânica', 'Curto no motor ou cabo', 'Drive com IGBT danificado'],
    solucoes: ['Verificar carga mecânica', 'Medir isolamento com megôhmetro', 'Substituir drive se IGBT danificado'],
    atencao: 'Usar megôhmetro 500V para verificar isolamento.'),
  AlarmeItem(codigo: 'P01', titulo: 'Program Error — Illegal Command',
    descricao: 'Comando ilegal encontrado no programa.',
    descricaoCompleta: 'CNC encontrou comando não executável.',
    gravidade: 'MÉDIO', categoria: 'Programação',
    causas: ['Código G/M inválido', 'Parâmetro fora da faixa', 'Opção não habilitada'],
    solucoes: ['Verificar bloco com erro', 'Consultar manual M70/M80', 'Verificar parâmetros'],
    atencao: null),
  AlarmeItem(codigo: 'Z70', titulo: 'Absolute Position Lost',
    descricao: 'Posição absoluta perdida — retorno ao zero necessário.',
    descricaoCompleta: 'Sistema de posição absoluta perdeu referência.',
    gravidade: 'MÉDIO', categoria: 'Referência',
    causas: ['Bateria descarregada', 'Falta de energia', 'Troca de encoder'],
    solucoes: ['ZERO RETURN em todos os eixos', 'Substituir bateria', 'Preventivo a cada 2 anos'],
    atencao: null),
];

// ─────────────────────────────────────────
// ALARMES HEIDENHAIN TNC — NOVO!
// ─────────────────────────────────────────
const alarmesHeidenhain = [
  AlarmeItem(codigo: 'ERR 251', titulo: 'Encoder: Signal Amplitude Too Small',
    descricao: 'Amplitude do sinal do encoder abaixo do mínimo aceitável.',
    descricaoCompleta: 'O sistema de medição linear ou rotativo enviou sinal com amplitude insuficiente. O TNC 640 não consegue posicionar com segurança.',
    gravidade: 'CRÍTICO', categoria: 'Encoder',
    causas: ['Régua linear ou encoder rotativo com sinal fraco', 'Conector do encoder com oxidação', 'Cabo do encoder danificado', 'Cabeçote leitora desalinhado ou sujo'],
    solucoes: ['Verificar e limpar o cabeçote leitora da régua', 'Inspecionar conector do encoder — limpar com álcool isopropílico', 'Verificar cabo — continuidade e blindagem', 'Ajustar gap entre régua e cabeçote (0.5-1.5mm típico)'],
    atencao: 'Não operar com sinal fraco — posicionamento incorreto pode causar colisão.'),

  AlarmeItem(codigo: 'ERR 252', titulo: 'Encoder: Signal Contamination',
    descricao: 'Contaminação no sistema de medição — sinal intermitente.',
    descricaoCompleta: 'O encoder ou régua linear detectou contaminação (óleo, fluido, cavaco) causando interferência no sinal de posição.',
    gravidade: 'ALTO', categoria: 'Encoder',
    causas: ['Fluido de corte entrando na régua linear', 'Cavaco contaminando o cabeçote leitora', 'Vedação da régua danificada', 'Ar comprimido insuficiente na purga'],
    solucoes: ['Limpar régua e cabeçote com ar comprimido seco', 'Verificar vedação da régua — substituir se danificada', 'Aumentar pressão de purga de ar (mín. 0.5 bar)', 'Verificar direcionamento do fluido de corte'],
    atencao: null),

  AlarmeItem(codigo: 'ERR 275', titulo: 'Drive: Motor Temperature Too High',
    descricao: 'Temperatura do motor servo do eixo acima do limite.',
    descricaoCompleta: 'O sensor de temperatura do motor servo detectou temperatura acima do limite seguro (geralmente 120°C). O TNC bloqueou o movimento para proteger o motor.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Trabalho contínuo em alta carga por longo período', 'Ventoinha de resfriamento do motor com defeito', 'Temperatura ambiente elevada no armário', 'Filtro de ar do armário entupido'],
    solucoes: ['Aguardar 20-30 minutos para resfriamento', 'Verificar ventoinha do motor servo', 'Verificar temperatura do armário (<40°C)', 'Limpar filtros de ar do armário elétrico'],
    atencao: null),

  AlarmeItem(codigo: 'ERR 300', titulo: 'Emergency Stop Activated',
    descricao: 'Parada de emergência acionada no TNC 640.',
    descricaoCompleta: 'O circuito de emergência foi ativado. Todos os eixos pararam imediatamente.',
    gravidade: 'ALTO', categoria: 'Segurança',
    causas: ['Botão de emergência pressionado', 'Porta de segurança aberta', 'Falha no relé de segurança', 'Sinal do CLP de emergência'],
    solucoes: ['Localizar e liberar botão de emergência', 'Verificar se todas as portas estão fechadas', 'Pressionar CE (Clear Error) no TNC', 'Verificar condições de segurança no CLP'],
    atencao: null),

  AlarmeItem(codigo: 'ERR 891', titulo: 'Software Limit: Positive Direction',
    descricao: 'Eixo atingiu o limite positivo de software.',
    descricaoCompleta: 'Um eixo tentou mover além do limite de curso positivo definido nos parâmetros de máquina MP600x.',
    gravidade: 'ALTO', categoria: 'Limite de Curso',
    causas: ['Preset (zero-peça) configurado incorretamente', 'Programa com coordenada além do curso', 'Parâmetro MP600x incorreto'],
    solucoes: ['Mover eixo na direção negativa (modo manual)', 'Verificar e corrigir preset ativo', 'Revisar programa — verificar coordenadas máximas', 'Conferir MP600x (limite positivo)'],
    atencao: null),

  AlarmeItem(codigo: 'ERR 1001', titulo: 'Tool Not In Spindle',
    descricao: 'Ferramenta não detectada no spindle — ATC com erro.',
    descricaoCompleta: 'O sensor de ferramenta do spindle não detectou a ferramenta após a troca. Pode estar presa no carrossel ou não fixada corretamente.',
    gravidade: 'CRÍTICO', categoria: 'Trocador',
    causas: ['Ferramenta não fixada no cone HSK ou SK', 'Pressão de ar insuficiente para o clamping', 'Sensor de ferramenta com defeito', 'Cone do spindle sujo ou danificado'],
    solucoes: ['PARAR IMEDIATAMENTE — não mover eixos', 'Verificar se ferramenta está presa no cone', 'Verificar pressão de ar (mín. 6 bar)', 'Limpar cone do spindle com pano limpo', 'Chamar técnico se ferramenta não liberar'],
    atencao: 'NUNCA mover eixos sem confirmação de ferramenta fixada. Risco de queda da ferramenta.'),

  AlarmeItem(codigo: 'ERR 3000', titulo: 'Contour Violation',
    descricao: 'Violação de contorno — ferramenta saiu do perfil programado.',
    descricaoCompleta: 'O TNC detectou que a ferramenta se desviou do contorno programado além do tolerado. Ocorre com adaptações de avanço ativas.',
    gravidade: 'ALTO', categoria: 'Contorno',
    causas: ['Override de avanço muito alto com adaptação automática', 'Ferramenta muito desgastada', 'Vibração excessiva causando desvio', 'Parâmetro de tolerância de contorno restritivo'],
    solucoes: ['Reduzir override para 80%', 'Verificar estado da ferramenta', 'Reduzir profundidade de corte', 'Ajustar parâmetro de tolerância de contorno no MP'],
    atencao: null),
];

// ─────────────────────────────────────────
// ALARMES OKUMA OSP — NOVO!
// ─────────────────────────────────────────
const alarmesOkuma = [
  AlarmeItem(codigo: 'AL-01', titulo: 'Emergency Stop',
    descricao: 'Parada de emergência ativada no controle OSP-P300.',
    descricaoCompleta: 'O circuito de emergência foi ativado no controle Okuma OSP. Todos os acionamentos foram desabilitados.',
    gravidade: 'ALTO', categoria: 'Segurança',
    causas: ['Botão de emergência pressionado', 'Porta de proteção aberta', 'Condição de segurança não satisfeita', 'Falha no módulo de segurança'],
    solucoes: ['Localizar e liberar botão de emergência (girar)', 'Confirmar que todas as portas estão fechadas', 'Verificar indicadores de segurança no painel', 'Pressionar RESET após liberar condições'],
    atencao: null),

  AlarmeItem(codigo: 'AL-02', titulo: 'Servo Alarm — Axis Overload',
    descricao: 'Sobrecarga detectada em eixo servo Okuma.',
    descricaoCompleta: 'A corrente do servo de um eixo excedeu o limite máximo. O controle OSP bloqueou o movimento para proteger o drive.',
    gravidade: 'CRÍTICO', categoria: 'Servo',
    causas: ['Carga mecânica excessiva no eixo', 'Ferramenta gasta aumentando esforço', 'Atrito nas guias por falta de lubrificação', 'Colisão ou interferência mecânica'],
    solucoes: ['Verificar obstrução mecânica nos eixos', 'Reduzir override de avanço para 25%', 'Verificar lubrificação das guias', 'Verificar estado da ferramenta'],
    atencao: 'Se alarme retornar imediatamente após reset, chamar técnico Okuma.'),

  AlarmeItem(codigo: 'AL-10', titulo: 'Servo Alarm — Encoder Error',
    descricao: 'Erro no encoder do servo — sinal de posição com falha.',
    descricaoCompleta: 'O sistema de posição Okuma detectou erro no encoder do motor servo. Pode ser falha de sinal ou hardware.',
    gravidade: 'CRÍTICO', categoria: 'Encoder',
    causas: ['Cabo do encoder com falha ou mau contato', 'Encoder danificado mecanicamente', 'Interferência eletromagnética no cabo', 'Conector do encoder com oxidação'],
    solucoes: ['Verificar cabo do encoder — continuidade e blindagem', 'Inspecionar conector do encoder — limpar pinos', 'Verificar se há interferência (cabos de potência próximos)', 'Substituir encoder se dano físico confirmado'],
    atencao: null),

  AlarmeItem(codigo: 'AL-20', titulo: 'Spindle Alarm — Overload',
    descricao: 'Sobrecarga no spindle Okuma.',
    descricaoCompleta: 'A corrente do motor spindle excedeu o limite. Carga de corte excessiva ou problema mecânico.',
    gravidade: 'ALTO', categoria: 'Spindle',
    causas: ['Profundidade ou largura de corte excessiva', 'Ferramenta desgastada ou quebrada', 'RPM muito baixo para o material', 'Rolamento do spindle com defeito'],
    solucoes: ['Reduzir override para 50%', 'Verificar e substituir ferramenta', 'Aumentar RPM ou reduzir avanço por dente', 'Verificar temperatura do spindle — máx. 60°C'],
    atencao: null),

  AlarmeItem(codigo: 'AL-30', titulo: 'ATC Alarm — Tool Change Incomplete',
    descricao: 'Troca automática de ferramenta não completada.',
    descricaoCompleta: 'O ATC Okuma não completou o ciclo de troca. Ferramenta pode estar presa ou sensor com defeito.',
    gravidade: 'CRÍTICO', categoria: 'Trocador',
    causas: ['Ferramenta presa no spindle ou no braço ATC', 'Pressão de ar insuficiente', 'Sensor de posição do ATC com defeito', 'Cone do spindle sujo'],
    solucoes: ['DESLIGAR a máquina antes de qualquer intervenção', 'Verificar visualmente se há ferramenta presa', 'Verificar pressão de ar (mín. 0.5 MPa / 5 bar)', 'Executar ATC INIT no menu de manutenção OSP'],
    atencao: 'NUNCA colocar as mãos na área do ATC com máquina ligada.'),

  AlarmeItem(codigo: 'AL-50', titulo: 'Hydraulic Pressure Alarm',
    descricao: 'Pressão hidráulica Okuma abaixo do mínimo.',
    descricaoCompleta: 'O sistema hidráulico não atingiu a pressão mínima necessária.',
    gravidade: 'ALTO', categoria: 'Hidráulica',
    causas: ['Bomba hidráulica com defeito ou desligada', 'Nível de óleo hidráulico baixo', 'Filtro hidráulico entupido', 'Válvula de pressão com vazamento'],
    solucoes: ['Verificar se motor da bomba hidráulica está ligado', 'Verificar nível de óleo no visor', 'Trocar filtro hidráulico (manutenção 500h)', 'Ajustar pressão: verificar manômetro (4.5-5.5 MPa)'],
    atencao: 'Não operar sem pressão hidráulica — pode soltar ferramenta durante corte.'),

  AlarmeItem(codigo: 'AL-100', titulo: 'Software Over-Travel — Positive',
    descricao: 'Eixo atingiu limite positivo de software no OSP.',
    descricaoCompleta: 'Um eixo tentou mover além do limite positivo de software configurado no OSP-P300.',
    gravidade: 'ALTO', categoria: 'Limite de Curso',
    causas: ['Zero-peça (Work Zero) configurado incorretamente', 'Programa com coordenada além do curso', 'Parâmetro de software limit incorreto'],
    solucoes: ['Mover eixo na direção negativa usando manivela (MPG)', 'Verificar e corrigir Work Zero ativo', 'Revisar programa — verificar coordenadas máximas'],
    atencao: 'Mover na direção oposta para liberar. Não forçar mecanicamente.'),

  AlarmeItem(codigo: 'AL-200', titulo: 'Program Error — Syntax Error',
    descricao: 'Erro de sintaxe no programa OSP.',
    descricaoCompleta: 'O controle OSP encontrou erro de sintaxe no programa NC. Verificar o bloco indicado.',
    gravidade: 'MÉDIO', categoria: 'Programação',
    causas: ['Código G ou M inválido para o OSP', 'Parâmetro fora da faixa permitida', 'Conflito entre comandos modais', 'Endereço de programação incorreto'],
    solucoes: ['Verificar o bloco indicado pelo alarme', 'Consultar manual de programação OSP-P300', 'Verificar se parâmetros estão na faixa correta', 'Usar verificação de programa do OSP antes de executar'],
    atencao: null),
];

// ─────────────────────────────────────────
// ALARMES ROMI — NOVO!
// ─────────────────────────────────────────
const alarmesRomi = [
  AlarmeItem(codigo: 'E-001', titulo: 'Emergência Ativada',
    descricao: 'Parada de emergência ativada no controle Romi.',
    descricaoCompleta: 'O circuito de emergência foi acionado. Todos os eixos e spindle pararam. Comum na Romi D600, GL240 e centros Galaxy.',
    gravidade: 'ALTO', categoria: 'Segurança',
    causas: ['Botão de emergência pressionado', 'Porta de proteção aberta', 'Falha no relé de segurança', 'Pressão hidráulica insuficiente'],
    solucoes: ['Girar e liberar botão de emergência', 'Fechar porta e verificar trava', 'Verificar relé de segurança', 'RESET no painel após liberar condições'],
    atencao: null),

  AlarmeItem(codigo: 'E-010', titulo: 'Erro de Comunicação — CLP',
    descricao: 'Falha de comunicação entre CNC e CLP interno da Romi.',
    descricaoCompleta: 'O CNC perdeu comunicação com o CLP interno. Paralisa funções auxiliares como ATC e refrigeração.',
    gravidade: 'CRÍTICO', categoria: 'Comunicação',
    causas: ['Cabo CNC-CLP danificado', 'CLP em STOP', 'Interferência eletromagnética', 'Placa de interface com defeito'],
    solucoes: ['Verificar cabo de comunicação', 'Reiniciar CLP no painel', 'Verificar aterramento da máquina', 'Contato Romi: 0800 722 7664'],
    atencao: 'A Romi possui suporte técnico nacional — 0800 722 7664.'),

  AlarmeItem(codigo: 'E-020', titulo: 'Sobrecarga Spindle — Motor Principal',
    descricao: 'Corrente do motor principal excedeu o limite no inversor.',
    descricaoCompleta: 'O inversor de frequência do motor principal detectou sobrecorrente. Comum em desbaste pesado nas séries Romi D e GL.',
    gravidade: 'ALTO', categoria: 'Spindle',
    causas: ['Profundidade de corte excessiva', 'Ferramenta desgastada', 'Material mais duro', 'RPM muito baixo'],
    solucoes: ['Reduzir override para 50%', 'Verificar e substituir ferramenta', 'Reduzir ap e fz', 'Aguardar 5min resfriamento do inversor'],
    atencao: null),

  AlarmeItem(codigo: 'E-030', titulo: 'Falha no Sistema Hidráulico',
    descricao: 'Pressão hidráulica abaixo de 35 kgf/cm² na Romi.',
    descricaoCompleta: 'Pressão hidráulica insuficiente. Afeta mandril, contra-ponta e fixação de ferramentas.',
    gravidade: 'ALTO', categoria: 'Hidráulica',
    causas: ['Motor da bomba desligado', 'Nível de óleo baixo', 'Filtro hidráulico entupido', 'Válvula mal regulada'],
    solucoes: ['Verificar motor da bomba (220/380V)', 'Completar óleo ISO VG 46', 'Trocar filtro (cada 500h)', 'Pressão correta: 50-60 kgf/cm²'],
    atencao: 'Verificar nível em temperatura normal de operação.'),

  AlarmeItem(codigo: 'E-040', titulo: 'Erro de Referência — Eixo',
    descricao: 'Eixo não completou o retorno ao zero (homing) na Romi.',
    descricaoCompleta: 'O eixo não encontrou o sinal de referência durante o homing. Comum após falta de energia.',
    gravidade: 'MÉDIO', categoria: 'Referência',
    causas: ['Dog sensor desalinhado', 'Encoder sem sinal de zero', 'Velocidade de homing alta', 'Bateria do encoder descarregada'],
    solucoes: ['Verificar posição do dog sensor', 'Reduzir velocidade de homing', 'Verificar bateria (CR17335, 3V)', 'ZERO RETURN manual no modo JOG'],
    atencao: null),

  AlarmeItem(codigo: 'E-050', titulo: 'Temperatura Excessiva — Armário',
    descricao: 'Temperatura interna do armário elétrico acima de 45°C.',
    descricaoCompleta: 'Sensor detectou temperatura acima do limite. Pode danificar inversores e placas.',
    gravidade: 'CRÍTICO', categoria: 'Temperatura',
    causas: ['Filtro de ar entupido', 'Ventilador com defeito', 'Temperatura ambiente alta', 'Resistor de frenagem superaquecido'],
    solucoes: ['Limpar filtros mensalmente', 'Verificar ventiladores', 'Verificar ar condicionado', 'Desligar e aguardar 20min'],
    atencao: 'NÃO religar com temperatura alta — inversores custam caro.'),

  AlarmeItem(codigo: 'E-060', titulo: 'Erro ATC — Troca de Ferramenta',
    descricao: 'Trocador automático não completou o ciclo na Romi.',
    descricaoCompleta: 'O ATC dos centros Romi Galaxy e I series não completou a troca.',
    gravidade: 'CRÍTICO', categoria: 'Trocador',
    causas: ['Ferramenta presa no cone BT40/BT50', 'Pressão de ar insuficiente', 'Sensor do braço com defeito', 'Cone sujo'],
    solucoes: ['DESLIGAR antes de intervir', 'Verificar pressão de ar (6-8 bar)', 'Limpar cone do spindle', 'ATC RESET pelo painel'],
    atencao: 'Sempre DESLIGAR antes de tocar no ATC.'),

  AlarmeItem(codigo: 'E-100', titulo: 'Over Travel — Limite de Curso',
    descricao: 'Eixo atingiu limite de software — mover na direção contrária.',
    descricaoCompleta: 'Um eixo ultrapassou o limite de curso configurado. Geralmente zero-peça incorreto.',
    gravidade: 'ALTO', categoria: 'Limite de Curso',
    causas: ['Zero-peça G54 incorreto', 'Coordenada além do curso', 'Offset de ferramenta errado'],
    solucoes: ['Mover na direção oposta (JOG/MPG)', 'Corrigir zero-peça', 'Revisar offsets H'],
    atencao: 'NUNCA forçar mecanicamente — pode danificar fuso de esferas.'),
];

// ─────────────────────────────────────────
// NOVOS CÓDIGOS G
// ─────────────────────────────────────────
const codigosGExtras = [

  CodigoItem(codigo: 'G10', nome: 'Entrada de Dados Programável', categoria: 'Programação', maquina: 'Ambos',
    descricao: 'Define offsets de ferramenta e zero-peça diretamente no programa.',
    descricaoCompleta: 'G10 permite definir ou alterar offsets (H, D) e zero-peças (G54-G59) no programa. Poderoso para automação — elimina ajuste manual.',
    sintaxe: 'G10 L[tipo] P[nº] R[valor]\nG10 L2 P1 X Y Z  ; Zero-peça G54\nG10 L10 P1 R[val] ; Offset H\nG10 L11 P1 R[val] ; Offset D',
    parametros: [
      Parametro('L', 'L2=zero-peça, L10=H geométrico, L11=D geométrico, L12=H desgaste, L13=D desgaste'),
      Parametro('P', 'Número do offset (1=H1/D1...)'),
      Parametro('R', 'Valor a definir'),
    ],
    exemplo: '; Define zero-peça G54:\nG10 L2 P1 X-350. Y-200. Z-100.\n;\n; Define H01 = 125.5mm:\nG10 L10 P1 R125.5\n;\n; Zera desgaste D01:\nG10 L13 P1 R0.0',
    explicacaoExemplo: 'Automação completa de offsets — sem ajuste manual do operador.', isG: true),

  CodigoItem(codigo: 'G12', nome: 'Fresamento Circular Horário', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Ciclo de bolsão circular horário — espiral crescente.',
    descricaoCompleta: 'G12 executa fresamento circular CW em espiral. I define o raio final do bolsão. Disponível em Fanuc e Haas.',
    sintaxe: 'G12 I[raio] F[av]',
    parametros: [Parametro('I', 'Raio final do bolsão'), Parametro('F', 'Avanço')],
    exemplo: 'G00 X50. Y30. Z5.\nG01 Z-5. F80.\nG12 I10. F150.  ; Bolsão Ø20mm\nG00 Z50.',
    explicacaoExemplo: 'I=10mm → bolsão Ø20mm em espiral horária.', isG: true),

  CodigoItem(codigo: 'G13', nome: 'Fresamento Circular Anti-horário', categoria: 'Ciclos Fixos', maquina: 'Centro de Usinagem',
    descricao: 'Ciclo de bolsão circular anti-horário — espiral CCW.',
    descricaoCompleta: 'G13 é igual ao G12 mas no sentido anti-horário. Para fresamento concordante em bolsões.',
    sintaxe: 'G13 I[raio] F[av]',
    parametros: [Parametro('I', 'Raio do bolsão'), Parametro('F', 'Avanço')],
    exemplo: 'G00 X0 Y0 Z5.\nG01 Z-8. F80.\nG13 I15. F150.  ; Bolsão Ø30mm\nG00 Z50.',
    explicacaoExemplo: 'I=15mm → bolsão Ø30mm anti-horário.', isG: true),

  CodigoItem(codigo: 'G16', nome: 'Coordenadas Polares', categoria: 'Programação', maquina: 'Centro de Usinagem',
    descricao: 'X = raio, Y = ângulo em graus. Ideal para furos em círculo.',
    descricaoCompleta: 'G16 ativa coordenadas polares. X = raio da posição, Y = ângulo em graus. Muito mais simples para furos em padrão circular do que calcular cos/sin.',
    sintaxe: 'G16  ; Ativa\nG[mov] X[raio] Y[ângulo] ...\nG15  ; Cancela',
    parametros: [Parametro('X', 'Raio'), Parametro('Y', 'Ângulo em graus (CCW)')],
    exemplo: '; 6 furos em R=40mm:\nG16\nG81 X40. Y0 Z-15. R2. F100   ; 0°\nX40. Y60.   ; 60°\nX40. Y120.  ; 120°\nX40. Y180.  ; 180°\nX40. Y240.  ; 240°\nX40. Y300.  ; 300°\nG80\nG15',
    explicacaoExemplo: 'Muito mais simples que calcular sin/cos para cada furo!', isG: true),

  CodigoItem(codigo: 'G15', nome: 'Cancela Coordenadas Polares', categoria: 'Programação', maquina: 'Centro de Usinagem',
    descricao: 'Retorna ao sistema cartesiano normal após G16.',
    descricaoCompleta: 'G15 cancela o modo de coordenadas polares do G16.',
    sintaxe: 'G15', parametros: [],
    exemplo: 'G16\nG01 X50. Y45. F200.\nG15  ; Volta ao cartesiano',
    explicacaoExemplo: 'Cancela polares — retorna X=mm, Y=mm normais.', isG: true),

  CodigoItem(codigo: 'G31', nome: 'Ciclo de Apalpamento (Skip Function)', categoria: 'Medição', maquina: 'Ambos',
    descricao: 'Move até tocar apalpador e captura posição no contato.',
    descricaoCompleta: 'G31 move o eixo até o apalpador ser ativado. A posição no contato é salva em #5061 (X), #5062 (Y), #5063 (Z). Essencial para medição automática em processo.',
    sintaxe: 'G31 X[val] Y[val] Z[val] F[av]',
    parametros: [Parametro('F', 'Avanço lento para precisão (ex: F50)'), Parametro('#5061-63', 'Variáveis com posição no contato X,Y,Z')],
    exemplo: '; Mede posição Z da superfície:\nG31 Z-50. F50.     ; Move até tocar\n#103 = #5063       ; Captura Z no toque\nG00 Z[#103 + 5.]   ; Sobe 5mm',
    explicacaoExemplo: 'Fundamental para medição automática em processo.', isG: true),

  CodigoItem(codigo: 'G43.4', nome: 'TCP — Tool Center Point (5 eixos)', categoria: 'Fresamento Avançado', maquina: 'Centro de Usinagem',
    descricao: 'Mantém ponto de controle na ponta da ferramenta em 5 eixos.',
    descricaoCompleta: 'G43.4 ativa o TCP para 5 eixos. Compensa automaticamente o comprimento quando eixos A, B ou C giram. Sem TCP, ao girar um eixo rotativo a ponta da ferramenta sai do ponto programado.',
    sintaxe: 'G43.4 H[n]',
    parametros: [Parametro('H', 'Offset de comprimento H da ferramenta')],
    exemplo: 'G43.4 H01\nG01 X50. Y30. Z-10. A30. B15. F200.\nG49   ; Cancela TCP',
    explicacaoExemplo: 'Essencial em 5 eixos — ponta sempre no ponto correto.', isG: true),
];

// ─────────────────────────────────────────
// GETTER — TODOS OS CÓDIGOS G COMBINADOS
// ─────────────────────────────────────────
List<CodigoItem> get todosCodigosG => [...codigosG, ...codigosGExtras];